Reduce the result set to only include what needs to be send
Energinet-DataHub/geh-aggregations pull request #101
Opened 2021-05-18 06:49 UTC by kristianschneider

Right now we send all steps to the coordinator.
This is not good because we also collect the data frames for each step and thereby vastly reduce performance

2021-05-18 07:00 UTC, ZavezX requested changes
Many of the results that are left out of the result set needs to be saved and sent to the coordinator. But I think it is a good idea to leave the ones out of the result set, that we don't need.

2021-05-18 07:27 UTC, mknic requested changes

2021-05-18 07:27 UTC, mknic commented on source/databricks/aggregation-jobs/aggregation_trigger.py
> +hourly_production_ga = aggregate_per_ga(results['hourly_production_with_system_correction_and_grid_loss'])
according to https://dev.azure.com/energinet/Datahub/_boards/board/t/Joules/Stories?workitem=102180 this should be added to the result

2021-05-18 07:27 UTC, mknic commented on source/databricks/aggregation-jobs/aggregation_trigger.py
> +hourly_settled_consumption_ga = aggregate_per_ga(results['hourly_consumption_df'])
according to https://dev.azure.com/energinet/Datahub/_boards/board/t/Joules/Stories?workitem=102180 this should be added to the result

2021-05-18 07:27 UTC, mknic commented on source/databricks/aggregation-jobs/aggregation_trigger.py
> +flex_settled_consumption_ga = aggregate_per_ga(flex_consumption_with_grid_loss)
according to https://dev.azure.com/energinet/Datahub/_boards/board/t/Joules/Stories?workitem=102180 this should be added to the result

2021-05-18 07:27 UTC, mknic commented on source/databricks/aggregation-jobs/aggregation_trigger.py
> +total_consumption = calculate_total_consumption(results['net_exchange_per_ga_df'], hourly_production_ga)
according to https://dev.azure.com/energinet/Datahub/_boards/board/t/Joules/Stories?workitem=102180 this should be added to the result

2021-05-18 07:27 UTC, mknic commented on source/databricks/aggregation-jobs/aggregation_trigger.py
> +hourly_production_ga_brp = aggregate_per_ga_and_brp(results['hourly_production_with_system_correction_and_grid_loss'])
according to https://dev.azure.com/energinet/Datahub/_boards/board/t/Joules/Stories?workitem=102179 this should be added to the result

2021-05-18 07:27 UTC, mknic commented on source/databricks/aggregation-jobs/aggregation_trigger.py
> +hourly_settled_consumption_ga_brp = aggregate_per_ga_and_brp(results['hourly_consumption_df'])
according to https://dev.azure.com/energinet/Datahub/_boards/board/t/Joules/Stories?workitem=102179 this should be added to the result

2021-05-18 07:27 UTC, mknic commented on source/databricks/aggregation-jobs/aggregation_trigger.py
> +flex_settled_consumption_ga_brp = aggregate_per_ga_and_brp(flex_consumption_with_grid_loss)
according to https://dev.azure.com/energinet/Datahub/_boards/board/t/Joules/Stories?workitem=102179 this should be added to the result

2021-05-18 07:27 UTC, mknic commented on source/databricks/aggregation-jobs/aggregation_trigger.py
> +# STEP 10 !
what does the `!` mean?

2021-05-18 07:27 UTC, mknic commented on source/databricks/aggregation-jobs/aggregation_trigger.py
> +# STEP 11 !
what does the `!` mean?

2021-05-18 07:30 UTC, mknic requested changes

2021-05-18 07:30 UTC, mknic commented on source/databricks/aggregation-jobs/aggregation_trigger.py
> +# STEP 1 !
I guess the `!` is to mark the steps being added to the result set? Maybe not that obvious though. Could we outline it in words instead maybe?

2021-05-18 07:32 UTC, kristianschneider commented on source/databricks/aggregation-jobs/aggregation_trigger.py
> +# STEP 1 !
Yes. Right now it was just for our own housekeeping

2021-05-18 07:44 UTC, mknic approved these changes

2021-05-18 07:48 UTC, ZavezX commented
I think we should keep the strategy to save all results from our aggregations regardless of performance, as we would need to store those results anyway. If we experience performance issues, then let's create a new task to fix it in another way. I suggest the PR to be abandoned.

2021-05-18 11:48 UTC, kristianschneider commented
@ZavezX Are you sure we need to store all steps ? That is not my impression

2021-05-18 12:49 UTC, mknic commented
@kristianschneider not all steps are used in the data packages sent to the post office but as far as I understand the end-users need to be able to see the results for all steps for each completed process so we need to store each result at some point.

2021-05-18 13:36 UTC, ZavezX approved these changes

2021-05-19 06:30 UTC, ZavezX requested changes

2021-05-19 06:30 UTC, ZavezX commented on source/databricks/aggregation-jobs/aggregation_trigger.py
> +grid_loss_df = calculate_grid_loss(results['net_exchange_per_ga_df'],
I think this would be good to keep.

2021-05-20 06:24 UTC, kristianschneider commented on source/databricks/aggregation-jobs/aggregation_trigger.py
> +grid_loss_df = calculate_grid_loss(results['net_exchange_per_ga_df'],
Done

2021-05-20 08:34 UTC, ZavezX approved these changes

2021-05-21 08:14 UTC, merged