This implements the ability to save snapshots of the aggregation source data
Energinet-DataHub/geh-aggregations pull request #104
Opened 2021-05-21 08:49 UTC by kristianschneider

2021-05-21 11:03 UTC, mknic requested changes
Looks good. One very minor suggested change and a question in regards to date format handling.

2021-05-21 11:03 UTC, mknic commented on source/databricks/geh_stream/aggregation_utils/services/aggregation_postprocessor.py
> +            stringFormatedTimeDf = value.withColumn("time_start", date_format(col("time_window.start"), "yyyy-MM-dd'T'HH:mm:ss'Z'")) \
I'm not sure what is up and down in the way of handling dates around the system, but I really don't like this hardcoded date format string. Wouldn't it be better to locate it somewhere else where all modules can reach it?

2021-05-21 11:49 UTC, mknic commented on source/databricks/geh_stream/aggregation_utils/aggregators/aggregate_quality.py
> +from pyspark.sql.functions import col, when, window, count, year, month, dayofmonth, hour,lit
Oh1 The `lit` can actually be removed. It looks like it's not used anymore.

2021-05-21 12:34 UTC, kristianschneider commented on source/databricks/geh_stream/aggregation_utils/services/aggregation_postprocessor.py
> +            stringFormatedTimeDf = value.withColumn("time_start", date_format(col("time_window.start"), "yyyy-MM-dd'T'HH:mm:ss'Z'")) \
We'll keep it until further

2021-05-21 12:35 UTC, ZavezX commented on source/coordinator/GreenEnergyHub.Aggregation.Coordinator/CoordinationTriggers.cs
> +                var snapshotPath = req.Headers["process-type"].First();
Should `snapshotPath` not map to another value?

2021-05-21 12:35 UTC, ZavezX commented on source/databricks/aggregation-jobs/aggregation_trigger.py
> +sys.path.append(r'/workspaces/geh-aggregations/source/databricks')
```suggestion
#import sys
#sys.path.append(r'/workspaces/geh-aggregations/source/databricks')
```

2021-05-21 12:35 UTC, ZavezX commented on source/databricks/geh_stream/aggregation_utils/aggregators/aggregate_quality.py
> +from pyspark.sql.functions import col, when, window, count, year, month, dayofmonth, hour, lit
```suggestion
from pyspark.sql.functions import col, when, window, count, year, month, dayofmonth, hour
```

2021-05-21 12:48 UTC, kristianschneider commented on source/coordinator/GreenEnergyHub.Aggregation.Coordinator/CoordinationTriggers.cs
> +                var snapshotPath = req.Headers["process-type"].First();
YES!

2021-05-25 06:29 UTC, mknic approved these changes

2021-05-25 07:01 UTC, johevemi approved these changes

2021-05-26 05:45 UTC, merged