Feature/102180 aggregation results
Energinet-DataHub/geh-aggregations pull request #106
Opened 2021-05-21 12:06 UTC by johevemi

## Description
Forwarded aggregation results with the correct recipients MDR, DDK and DDX

## References

* #0000

2021-05-21 12:46 UTC, ZavezX commented on source/coordinator/GreenEnergyHub.Aggregation.Application/Coordinator/CoordinatorService.cs
> +        public async Task StartAggregationJobAsync(string processType, Instant beginTime, Instant endTime, string resultId, CancellationToken cancellationToken)
Why was `processType` changed from `Enum` to `String`

2021-05-21 12:52 UTC, ZavezX commented on source/coordinator/GreenEnergyHub.Aggregation.Domain/DTOs/AggregationResultDto.cs
> +        public double SumQuantity { get; set; }
`SumQuantity` should be a `decimal`.

2021-05-21 12:52 UTC, ZavezX commented on source/coordinator/GreenEnergyHub.Aggregation.Domain/DTOs/AggregationResultDto.cs
> +        public TimeWindowDto TimeWindow { get; set; }
`TimeWindow` is split into two date properties in python results. So this should be `public Instant TimeStart` and `public Instant TimeEnd`.

2021-05-21 12:52 UTC, ZavezX commented on source/coordinator/GreenEnergyHub.Aggregation.Domain/DTOs/TimeWindowDto.cs
>      }
This dto can be deleted.

2021-05-25 06:51 UTC, jonasdmoeller commented on source/coordinator/GreenEnergyHub.Aggregation.Application/Coordinator/CoordinatorService.cs
> +        public async Task StartAggregationJobAsync(string processType, Instant beginTime, Instant endTime, string resultId, CancellationToken cancellationToken)
Because we get processType as a string input and it should also be a string when output - without any manipulation. So converting it to an enum is unnecessary.

2021-05-25 12:02 UTC, ZavezX commented on source/coordinator/GreenEnergyHub.Aggregation.Application/Coordinator/CoordinatorService.cs
> +        public async Task StartAggregationJobAsync(string processType, Instant beginTime, Instant endTime, string resultId, CancellationToken cancellationToken)
But that could also be said about `beginTime` and `endTime` as well, and we convert those to `Instant`.

2021-05-25 12:53 UTC, ZavezX requested changes

2021-05-25 12:53 UTC, ZavezX commented on source/coordinator/GreenEnergyHub.Aggregation.Tests/Assets/Exchange.json
> +    "sum_quantity": -32.000,
Should be `time_start` not `time_time_start`.

2021-05-25 12:53 UTC, ZavezX commented on source/coordinator/GreenEnergyHub.Aggregation.Tests/Assets/Exchange.json
> +    "time_time_start": "2020-10-03T08:00:00.000Z",
Same here.

2021-05-26 06:13 UTC, jonasdmoeller commented on source/coordinator/GreenEnergyHub.Aggregation.Application/Coordinator/Strategies/ProductionStrategy.cs
> +            // TODO: Should not dispatch
Fixed

2021-05-26 06:14 UTC, jonasdmoeller commented on source/coordinator/GreenEnergyHub.Aggregation.Application/Coordinator/ICoordinatorService.cs
> +        Task StartAggregationJobAsync(string processType, Instant beginTime, Instant endTime, string resultId, CancellationToken cancellationToken);
See above comment

2021-05-26 06:15 UTC, jonasdmoeller commented on source/coordinator/GreenEnergyHub.Aggregation.Tests/Assets/Exchange.json
> +    "sum_quantity": -32.000,
Fixed

2021-05-26 06:15 UTC, jonasdmoeller commented on source/coordinator/GreenEnergyHub.Aggregation.Tests/Assets/Exchange.json
> +    "time_time_start": "2020-10-03T08:00:00.000Z",
Fixed

2021-05-26 06:16 UTC, jonasdmoeller commented on source/coordinator/GreenEnergyHub.Aggregation.Application/Coordinator/CoordinatorService.cs
> +        public async Task StartAggregationJobAsync(string processType, Instant beginTime, Instant endTime, string resultId, CancellationToken cancellationToken)
Then why do we convert those to instants?

2021-05-26 10:22 UTC, mknic commented on source/coordinator/GreenEnergyHub.Aggregation.Application/Coordinator/CoordinatorService.cs
> +        public async Task StartAggregationJobAsync(string processType, Instant beginTime, Instant endTime, string resultId, CancellationToken cancellationToken)
@ZavezX @jonasdmoeller to me those two scenarious are two different discussions. `ProcessType` is a string and was an enum because of readaility. `Instant` is used for handling dates to avoid having dates as strings floating around the system. I guess this work was done by @ftoft and @johevemi when they refactored a lot of the usages of dates.

2021-05-27 10:49 UTC, kristianschneider approved these changes

2021-05-27 10:51 UTC, ZavezX approved these changes

2021-05-27 10:51 UTC, merged