Change dto sent to CreateMessage and adjust unit test
Energinet-DataHub/geh-aggregations pull request #111
Opened 2021-05-28 11:05 UTC by johevemi

## Description

Corrects a mistake made in #106 where the wrong dto was sent to CreateMessage in exchange and exchange neighbor strategies 

## References

* #0000

2021-05-28 11:07 UTC, kristianschneider approved these changes

2021-05-28 12:03 UTC, ZavezX requested changes

2021-05-28 12:03 UTC, ZavezX commented on source/coordinator/GreenEnergyHub.Aggregation.Tests/Step01ExchangePerNeighbourStrategyTests.cs
> +            message.EnergyObservation.Should().HaveCount(1); // there should be only have 1 EnergyObservations in grid area 500, see ExchangeNeighbour.json
When selecting message you could filter the message for only grid area 500, that way the code isn't vulnerable to changes to the test file.

2021-05-28 12:03 UTC, ZavezX commented on source/coordinator/GreenEnergyHub.Aggregation.Tests/Step02ExchangeStrategyTests.cs
> +            message.EnergyObservation.Should().HaveCount(2); // there should be only have 2 EnergyObservations in grid area 500, see Exchange.json
Same here as stated above.

2021-05-31 12:45 UTC, johevemi commented on source/coordinator/GreenEnergyHub.Aggregation.Tests/Step01ExchangePerNeighbourStrategyTests.cs
> +            message.EnergyObservation.Should().HaveCount(1); // there should be only have 1 EnergyObservations in grid area 500, see ExchangeNeighbour.json
as the test is right now, we want it to fail if the test data is changed

2021-05-31 12:46 UTC, johevemi commented on source/coordinator/GreenEnergyHub.Aggregation.Tests/Step02ExchangeStrategyTests.cs
> +            message.EnergyObservation.Should().HaveCount(2); // there should be only have 2 EnergyObservations in grid area 500, see Exchange.json
as the test is right now, we want it to fail if the test data is changed

2021-05-31 13:01 UTC, ZavezX approved these changes

2021-05-31 13:01 UTC, merged