Feature/128190 meta data dal in coordinator
Energinet-DataHub/geh-aggregations pull request #126
Opened 2021-06-16 07:38 UTC by ftoft

## Description

Implementation of DAL for MetaData

## References

* #0000

2021-06-16 11:56 UTC, kristianschneider commented on source/coordinator/GreenEnergyHub.Aggregation.DatabaseMigration/001_JobsTable.cs
>  using FluentMigrator;
We might need to wait for the DbUp PR to get into main which is the new way to create the schemas

2021-06-21 12:28 UTC, jonasdmoeller requested changes

2021-06-21 12:28 UTC, jonasdmoeller commented on source/coordinator/GreenEnergyHub.Aggregation.Infrastructure/MetaDataDataAccess.cs
> +﻿// Copyright 2020 Energinet DataHub A/S
Using parameters 'job' and 'result' can lead to null pointer exceptions

2021-06-21 12:28 UTC, jonasdmoeller commented on source/coordinator/GreenEnergyHub.Aggregation.Infrastructure/MetaDataDataAccess.cs
> +﻿// Copyright 2020 Energinet DataHub A/S
await all async calls

2021-06-21 12:28 UTC, jonasdmoeller commented on source/coordinator/GreenEnergyHub.Aggregation.Infrastructure/MetaDataDataAccess.cs
> +﻿// Copyright 2020 Energinet DataHub A/S
Configure await when awaiting async calls

2021-06-21 12:28 UTC, jonasdmoeller commented on source/coordinator/GreenEnergyHub.Aggregation.Infrastructure/MetaDataDataAccess.cs
> +﻿// Copyright 2020 Energinet DataHub A/S
await using statements

2021-06-21 12:28 UTC, jonasdmoeller commented on source/coordinator/GreenEnergyHub.Aggregation.Tests/InputProcessorTests.cs
>          [Fact]
We should rename unit test cases to follow the given-when-then pattern, i.e. given an unknown stragegy, when process input is called, an exception is thrown. So method name would be something like:
`public async Task UnknownStrategy_ProcessInput_ExceptionIsThrow()` or something like that..

2021-06-22 08:38 UTC, merged

2021-06-22 09:16 UTC, jonasdmoeller commented
@kristianschneider Why was this pull request merged before review approval?