Feature/138523 chargelinks test data
Energinet-DataHub/geh-aggregations pull request #138
Opened 2021-07-01 12:33 UTC by kristianschneider

This implements charge links and charge prices and introduced a more generics approach for handling parsing

2021-07-01 13:00 UTC, johevemi approved these changes

2021-07-02 06:24 UTC, johevemi approved these changes

2021-07-02 07:33 UTC, mknic approved these changes

2021-07-02 07:37 UTC, merged

2021-07-02 07:45 UTC, ZavezX requested changes

2021-07-02 07:45 UTC, ZavezX commented on source/test-data-generation/GreenEnergyHub.Aggregation.TestData.Application/Parsers/ChargeLinkTestDataParser.cs
> +        public override string FileNameICanHandle => "ChargeLinks.csv";
Maybe we should move the file name to an app setting as these filenames could potentially change or be different in the first place.

2021-07-02 07:45 UTC, ZavezX commented on source/test-data-generation/GreenEnergyHub.Aggregation.TestData.Application/Parsers/ChargePriceTestDataParser.cs
> +        public override string FileNameICanHandle => "ChargePrices.csv";
Same goes here.

2021-07-02 07:45 UTC, ZavezX commented on source/test-data-generation/GreenEnergyHub.Aggregation.TestData.Application/Parsers/ChargeTestDataParser.cs
>          public override string FileNameICanHandle => "charges.csv";
Here as well.

2021-07-02 07:46 UTC, ZavezX commented
@kristianschneider I was a bit late to the review party, but I have some comments on this one.