fix for logging issue and better upload handling
Energinet-DataHub/geh-aggregations pull request #146
Opened 2021-07-07 08:05 UTC by kristianschneider

This fixes an issue with generator logging and also improces the csv upload process

2021-07-07 08:16 UTC, mknic requested changes

2021-07-07 08:16 UTC, mknic commented on source/test-data-generation/GreenEnergyHub.Aggregation.TestData.Infrastructure/CosmosDb/MasterDataStorage.cs
> +                CreateContainerIfNotExistsAsync(containerName, "/pk").
Should we pass `partionKeyPath` as parameter? I guess it would change from `/pk` and be different in the diff. containers.

2021-07-07 08:23 UTC, kristianschneider commented on source/test-data-generation/GreenEnergyHub.Aggregation.TestData.Infrastructure/CosmosDb/MasterDataStorage.cs
> +                CreateContainerIfNotExistsAsync(containerName, "/pk").
That would require even more configuration and for the test data its not so important since we dont have much data

2021-07-07 08:35 UTC, mknic approved these changes

2021-07-07 08:46 UTC, johevemi approved these changes

2021-07-07 12:01 UTC, merged

2021-07-26 08:04 UTC, ZavezX commented on source/test-data-generation/GreenEnergyHub.Aggregation.TestData.Infrastructure/Models/Charge.cs
> +                return instant;
This could be moved to a general implementation that can be used other places too, instead of having duplicate code.

2021-07-26 08:04 UTC, ZavezX commented on source/test-data-generation/GreenEnergyHub.Aggregation.TestData.Infrastructure/Models/Charge.cs
> +                return instant;
See comment above.

2021-07-26 08:04 UTC, ZavezX commented on source/test-data-generation/GreenEnergyHub.Aggregation.TestData.Infrastructure/Models/ChargeLink.cs
> +                return instant;
See comment above.

2021-07-26 08:04 UTC, ZavezX commented on source/test-data-generation/GreenEnergyHub.Aggregation.TestData.Infrastructure/Models/ChargeLink.cs
> +                return instant;
See comment above.

2021-07-26 08:04 UTC, ZavezX commented on source/test-data-generation/GreenEnergyHub.Aggregation.TestData.Infrastructure/Models/ChargePrice.cs
> +                return instant;
See comment above.

2021-07-26 08:04 UTC, ZavezX commented on source/test-data-generation/GreenEnergyHub.Aggregation.TestData.Infrastructure/Models/MarketRole.cs
> +                return instant;
See comment above.

2021-07-26 08:04 UTC, ZavezX commented on source/test-data-generation/GreenEnergyHub.Aggregation.TestData.Infrastructure/Models/MarketRole.cs
> +                return instant;
See comment above.

2021-07-26 08:04 UTC, ZavezX commented on source/test-data-generation/GreenEnergyHub.Aggregation.TestData.Infrastructure/Models/MeteringPoint.cs
> +                return instant;
See comment above.

2021-07-26 08:04 UTC, ZavezX commented on source/test-data-generation/GreenEnergyHub.Aggregation.TestData.Infrastructure/Models/MeteringPoint.cs
> +                return instant;
See comment above.

2021-07-26 08:04 UTC, ZavezX commented on source/test-data-generation/GreenEnergyHub.Aggregation.TestData.Infrastructure/Models/SpecialMeteringPoint.cs
> +                return instant;
See comment above.

2021-07-26 08:04 UTC, ZavezX commented on source/test-data-generation/GreenEnergyHub.Aggregation.TestData.Infrastructure/Models/SpecialMeteringPoint.cs
> +                return instant;
See comment above.