WIP
Energinet-DataHub/geh-aggregations pull request #205
Opened 2021-08-03 07:53 UTC by kristianschneider

## Description

## References

* #0000

2021-08-04 07:27 UTC, ZavezX commented
There is still a reference to protobuf in `CoordinatorFunction` project:
![devenv_9G9pA1VdFL](https://user-images.githubusercontent.com/3176163/128139642-7e19c51d-170f-4bbc-9973-46e949f89d48.png)

2021-08-04 07:28 UTC, ZavezX commented
I see there is a reference to project `DatabaseMigration` in project `Application`. Why is this here? It seems like it shouldn't?

![devenv_ceFHCm7wuX](https://user-images.githubusercontent.com/3176163/128139870-bf26eb15-0839-450b-bbd4-06fcfa8d1f81.png)

2021-08-04 07:33 UTC, ZavezX commented
This line can be removed as it's not used:

https://github.com/Energinet-DataHub/geh-aggregations/blob/4cb7873fbe86ab6c7428dc96f0c72686f70a7ae9/source/coordinator/GreenEnergyHub.Aggregation.Application/Coordinator/CoordinatorService.cs#L17

2021-08-04 08:26 UTC, ZavezX commented
Unused using can be removed:
https://github.com/Energinet-DataHub/geh-aggregations/blob/4cb7873fbe86ab6c7428dc96f0c72686f70a7ae9/source/coordinator/GreenEnergyHub.Aggregation.Tests/ConsumptionStrategiesTests.cs#L23

2021-08-04 08:27 UTC, ZavezX commented
Unused using can be removed:
https://github.com/Energinet-DataHub/geh-aggregations/blob/4cb7873fbe86ab6c7428dc96f0c72686f70a7ae9/source/coordinator/GreenEnergyHub.Aggregation.Tests/InputProcessorTests.cs#L24

2021-08-04 08:35 UTC, ZavezX commented
There are two files that seem a little odd to me as it looks like they shouldn't be there:
https://github.com/Energinet-DataHub/geh-aggregations/blob/4cb7873fbe86ab6c7428dc96f0c72686f70a7ae9/source/messaging/source/GreenEnergyHub.Messaging.Protobuf/ProtobufOutboundMapper%601.cs
https://github.com/Energinet-DataHub/geh-aggregations/blob/4cb7873fbe86ab6c7428dc96f0c72686f70a7ae9/source/messaging/source/GreenEnergyHub.Messaging.Protobuf/ProtobufInboundMapper%601.cs

2021-08-04 08:47 UTC, ZavezX requested changes
Very nice work on this! Just a lot of unused usings and some questions along the way.

2021-08-04 08:47 UTC, ZavezX commented on source/coordinator/GreenEnergyHub.Aggregation.Application/Coordinator/Strategies/Step01ExchangePerNeighbourStrategy.cs
>  using System;
Unused using.
```suggestion
```

2021-08-04 08:47 UTC, ZavezX commented on source/coordinator/GreenEnergyHub.Aggregation.Application/Coordinator/Strategies/Step02ExchangeStrategy.cs
>  using System;
Unused using.
```suggestion
```

2021-08-04 08:47 UTC, ZavezX commented on source/coordinator/GreenEnergyHub.Aggregation.Application/Coordinator/Strategies/Step02ExchangeStrategy.cs
>  using GreenEnergyHub.Aggregation.Domain;
Unused using.
```suggestion
```

2021-08-04 08:47 UTC, ZavezX commented on source/coordinator/GreenEnergyHub.Aggregation.Application/Coordinator/Strategies/Step03HourlyConsumptionStrategy.cs
>  using System;
Unused using.
```suggestion
```

2021-08-04 08:47 UTC, ZavezX commented on source/coordinator/GreenEnergyHub.Aggregation.Application/Coordinator/Strategies/Step0809CombinedGridLossStrategy.cs
>  using System;
Unused using.
```suggestion
```

2021-08-04 08:47 UTC, ZavezX commented on source/coordinator/GreenEnergyHub.Aggregation.Application/Coordinator/Strategies/Step10FlexConsumptionStrategy.cs
>  using System;
Unused using.
```suggestion
```

2021-08-04 08:47 UTC, ZavezX commented on source/coordinator/GreenEnergyHub.Aggregation.Application/Coordinator/Strategies/Step11ProductionStrategy.cs
>  using System;
Unused using.
```suggestion
```

2021-08-04 08:47 UTC, ZavezX commented on source/coordinator/GreenEnergyHub.Aggregation.Application/Coordinator/Strategies/Step12ProductionPerSupplierStrategy.cs
>  using System;
Unused using.
```suggestion
```

2021-08-04 08:47 UTC, ZavezX commented on source/coordinator/GreenEnergyHub.Aggregation.Application/Coordinator/Strategies/Step13HourlyConsumptionPerSupplierStrategy.cs
>  using System;
Unused using.
```suggestion
```

2021-08-04 08:47 UTC, ZavezX commented on source/coordinator/GreenEnergyHub.Aggregation.Application/Coordinator/Strategies/Step14FlexConsumptionPerSupplierStrategy.cs
>  using System;
Unused using.
```suggestion
```

2021-08-04 08:47 UTC, ZavezX commented on source/coordinator/GreenEnergyHub.Aggregation.Application/Coordinator/Strategies/Step15ProductionPerBrpStrategy.cs
>  using System;
Unused using.
```suggestion
```

2021-08-04 08:47 UTC, ZavezX commented on source/coordinator/GreenEnergyHub.Aggregation.Application/Coordinator/Strategies/Step16HourlyConsumptionPerBrpStrategy.cs
>  using System;
Unused using.
```suggestion
```

2021-08-04 08:47 UTC, ZavezX commented on source/coordinator/GreenEnergyHub.Aggregation.Application/Coordinator/Strategies/Step17FlexConsumptionPerBrpStrategy.cs
>  using System;
Unused using.
```suggestion
```

2021-08-04 08:47 UTC, ZavezX commented on source/coordinator/GreenEnergyHub.Aggregation.Application/Coordinator/Strategies/Step18ProductionPerGridAreaStrategy.cs
>  using System;
Unused using.
```suggestion
```

2021-08-04 08:47 UTC, ZavezX commented on source/coordinator/GreenEnergyHub.Aggregation.Application/Coordinator/Strategies/Step19HourlyConsumptionPerGridAreaStrategy.cs
>  using System;
Unused using.
```suggestion
```

2021-08-04 08:47 UTC, ZavezX commented on source/coordinator/GreenEnergyHub.Aggregation.Application/Coordinator/Strategies/Step20FlexConsumptionPerGridAreaStrategy.cs
>  using System;
Unused using.
```suggestion
```

2021-08-04 08:47 UTC, ZavezX commented on source/coordinator/GreenEnergyHub.Aggregation.Application/Coordinator/Strategies/Step21TotalConsumptionPerGridAreaStrategy.cs
>  using System;
Unused using.
```suggestion
```

2021-08-04 08:47 UTC, ZavezX commented on source/coordinator/GreenEnergyHub.Aggregation.Application/GreenEnergyHub.Aggregation.Application.csproj
>      <ProjectReference Include="..\GreenEnergyHub.Aggregation.DatabaseMigration\GreenEnergyHub.Aggregation.DatabaseMigration.csproj" />
Why is this reference in the application project?

2021-08-04 08:47 UTC, ZavezX commented on source/coordinator/GreenEnergyHub.Aggregation.Infrastructure/ServiceBusProtobuf/MeteringPointMessageToDtoMapper.cs
> +using GreenEnergyHub.Aggregation.Domain.DTOs;
Unused using.
```suggestion
```

2021-08-04 08:47 UTC, ZavezX commented on source/coordinator/GreenEnergyHub.Aggregation.Infrastructure/ServiceBusProtobuf/TimeSeriesDispatcher.cs
> +using GreenEnergyHub.Aggregation.Application.Coordinator.Interfaces;
Unused using.
```suggestion
```

2021-08-04 08:47 UTC, ZavezX commented on source/messaging/source/GreenEnergyHub.Messaging.Integration.ServiceCollection/HandlerExtensions.cs
> +using GreenEnergyHub.Aggregation.Domain.DTOs;
Unused using.
```suggestion
```

2021-08-04 08:47 UTC, ZavezX commented on source/messaging/source/GreenEnergyHub.Messaging.Protobuf/ProtobufMessageSerializer.cs
> +using GreenEnergyHub.Aggregation.Application.Coordinator.Interfaces;
Unused using.
```suggestion
```

2021-08-04 08:47 UTC, ZavezX commented on source/messaging/source/GreenEnergyHub.Messaging.Protobuf/ProtobufMessageSerializer.cs
> +using GreenEnergyHub.Aggregation.Domain.DTOs;
Unused using.
```suggestion
```

2021-08-04 08:47 UTC, ZavezX commented on source/messaging/source/GreenEnergyHub.Messaging.Protobuf/ProtobufOutboundMapper.cs
> +using GreenEnergyHub.Aggregation.Application.Coordinator.Interfaces;
Unused using.
```suggestion
```

2021-08-04 08:47 UTC, ZavezX commented on source/messaging/source/GreenEnergyHub.Messaging.Protobuf/ProtobufOutboundMapper.cs
>  using GreenEnergyHub.Messaging.Transport;
Unused using.
```suggestion
```

2021-08-04 08:47 UTC, ZavezX commented on source/messaging/source/GreenEnergyHub.Messaging.Protobuf/ProtobufOutboundMapperFactory.cs
> +using GreenEnergyHub.Aggregation.Domain.DTOs;
Unused using.
```suggestion
```

2021-08-04 08:47 UTC, ZavezX commented on source/messaging/source/GreenEnergyHub.Messaging/Dispatching/BaseCommandHandler.cs
> +using GreenEnergyHub.Aggregation.Domain.DTOs;
Unused using.
```suggestion
```

2021-08-04 08:47 UTC, ZavezX commented on source/messaging/source/GreenEnergyHub.Messaging/Dispatching/BaseRequestHandler.cs
> +using GreenEnergyHub.Aggregation.Domain.DTOs;
Unused using.
```suggestion
```

2021-08-04 08:47 UTC, ZavezX commented on source/messaging/source/GreenEnergyHub.Messaging/Dispatching/HubCommand.cs
> +using GreenEnergyHub.Aggregation.Domain.DTOs;
Unused using.
```suggestion
```

2021-08-04 08:47 UTC, ZavezX commented on source/messaging/source/GreenEnergyHub.Messaging/Dispatching/HubCommandHandler.cs
> +using GreenEnergyHub.Aggregation.Domain.DTOs;
Unused using.
```suggestion
```

2021-08-04 08:47 UTC, ZavezX commented on source/messaging/source/GreenEnergyHub.Messaging/Dispatching/HubCommandMediator.cs
> + using GreenEnergyHub.Aggregation.Domain.DTOs;
Unused using.
```suggestion
```

2021-08-04 08:47 UTC, ZavezX commented on source/messaging/source/GreenEnergyHub.Messaging/Dispatching/HubRequest.cs
> +using GreenEnergyHub.Aggregation.Domain.DTOs;
Unused using.
```suggestion
```

2021-08-04 08:47 UTC, ZavezX commented on source/messaging/source/GreenEnergyHub.Messaging/Dispatching/HubRequestHandler.cs
> +using GreenEnergyHub.Aggregation.Domain.DTOs;
Unused using.
```suggestion
```

2021-08-04 08:47 UTC, ZavezX commented on source/messaging/source/GreenEnergyHub.Messaging/Dispatching/HubRequestMediator.cs
> +using GreenEnergyHub.Aggregation.Domain.DTOs;
Unused using.
```suggestion
```

2021-08-04 08:47 UTC, ZavezX commented on source/messaging/source/GreenEnergyHub.Messaging/Dispatching/IHubCommandMediator.cs
> +using GreenEnergyHub.Aggregation.Domain.DTOs;
Unused using.
```suggestion
```

2021-08-04 08:47 UTC, ZavezX commented on source/messaging/source/GreenEnergyHub.Messaging/Dispatching/IHubRequestBulkMediator.cs
> +using GreenEnergyHub.Aggregation.Domain.DTOs;
Unused using.
```suggestion
```

2021-08-04 08:47 UTC, ZavezX commented on source/messaging/source/GreenEnergyHub.Messaging/Dispatching/IHubRequestMediator.cs
> +using GreenEnergyHub.Aggregation.Domain.DTOs;
Unused using.
```suggestion
```

2021-08-04 08:47 UTC, ZavezX commented on source/messaging/source/GreenEnergyHub.Messaging/IHubRehydrate.cs
> +using GreenEnergyHub.Aggregation.Domain.DTOs;
Unused using.
```suggestion
```

2021-08-04 08:47 UTC, ZavezX commented on source/messaging/source/GreenEnergyHub.Messaging/JsonSerializerWithOption.cs
> +using GreenEnergyHub.Aggregation.Application.Coordinator.Interfaces;
Unused using.
```suggestion
```

2021-08-04 08:47 UTC, ZavezX commented on source/messaging/source/GreenEnergyHub.Messaging/Transport/IInboundMessage.cs
> +using GreenEnergyHub.Aggregation.Domain.DTOs;
Unused using.
```suggestion
```

2021-08-04 08:47 UTC, ZavezX commented on source/messaging/source/GreenEnergyHub.Messaging/Transport/MessageDispatcher.cs
> +using GreenEnergyHub.Aggregation.Domain.DTOs;
Unused using.
```suggestion
```

2021-08-04 08:47 UTC, ZavezX commented on source/messaging/source/GreenEnergyHub.Messaging/Transport/MessageSerializer.cs
> +using GreenEnergyHub.Aggregation.Application.Coordinator.Interfaces;
Unused using.
```suggestion
```

2021-08-04 08:47 UTC, ZavezX commented on source/messaging/source/GreenEnergyHub.Messaging/Transport/MessageSerializer.cs
> +using GreenEnergyHub.Aggregation.Domain.DTOs;
Unused using.
```suggestion
```

2021-08-09 13:01 UTC, kristianschneider commented
> There is still a reference to protobuf in `CoordinatorFunction` project:
> 
> ![devenv_9G9pA1VdFL](https://user-images.githubusercontent.com/3176163/128139642-7e19c51d-170f-4bbc-9973-46e949f89d48.png)

It is required for DI of 
`            builder.Services.SendProtobuf<Document>();
`
As far as I understand it's ok for the executing part to know infrastructure

2021-08-09 13:08 UTC, kristianschneider commented
> I see there is a reference to project `DatabaseMigration` in project `Application`. Why is this here? It seems like it shouldn't?
> 
> ![devenv_ceFHCm7wuX](https://user-images.githubusercontent.com/3176163/128139870-bf26eb15-0839-450b-bbd4-06fcfa8d1f81.png)

It is used to package the migration dll into the application artifact. It is to prevent having to create an entire deployment pipeline just for the database migration. Personally I don't have a nit with it. But if we find that this should be the case I suggest we create a story for it

2021-08-09 13:09 UTC, kristianschneider commented on source/coordinator/GreenEnergyHub.Aggregation.Application/GreenEnergyHub.Aggregation.Application.csproj
>      <ProjectReference Include="..\GreenEnergyHub.Aggregation.DatabaseMigration\GreenEnergyHub.Aggregation.DatabaseMigration.csproj" />
Se my comment below

2021-08-09 17:50 UTC, ZavezX approved these changes

2021-08-09 17:51 UTC, ZavezX commented
@kristianschneider Just a few conflicts and this looks good!

2021-08-10 07:37 UTC, jonasdmoeller approved these changes

2021-08-10 08:23 UTC, merged