Feature/199 metadata update
Energinet-DataHub/geh-aggregations pull request #225
Opened 2021-08-11 06:11 UTC by kristianschneider

This implements the feature for  **Update MetaData when aggregation or wholesale job are created**

2021-08-11 11:59 UTC, johevemi approved these changes

2021-08-11 13:14 UTC, mknic requested changes
Very nice having enum representations added to the code!

2021-08-11 13:14 UTC, mknic commented on source/coordinator/GreenEnergyHub.Aggregation.Application/Coordinator/CoordinatorService.cs
> +using JobStateEnum = GreenEnergyHub.Aggregation.Domain.DTOs.MetaData.JobStateEnum;
We already have a reference to `GreenEnergyHub.Aggregation.Domain.DTOs.MetaData` and other enums located there are accessible so I think the `using` can be removed.

2021-08-11 13:14 UTC, mknic commented on source/coordinator/GreenEnergyHub.Aggregation.Application/Coordinator/CoordinatorSettings.cs
> +        public const string ClusterAggregationJobName = "Aggregation JobMetadata";
Not sure I get the point of renaming the name of the job to include `Metadata`?

2021-08-11 13:14 UTC, mknic commented on source/coordinator/GreenEnergyHub.Aggregation.Application/Coordinator/CoordinatorSettings.cs
> +        public const string ClusterWholesaleJobName = "Wholesale JobMetadata";
Same here

2021-08-12 06:08 UTC, kristianschneider commented on .gitignore
> +*launchSettings.json
I scratched my own itch, so I think it should be applicable to others. I does not harm anything

2021-08-12 06:12 UTC, kristianschneider commented on source/coordinator/GreenEnergyHub.Aggregation.Application/Coordinator/CoordinatorSettings.cs
> +        public const string ClusterAggregationJobName = "Aggregation JobMetadata";
To aggressive autorenaming :-)

2021-08-12 06:18 UTC, mknic approved these changes
LGTM

2021-08-12 08:20 UTC, ZavezX requested changes

2021-08-12 08:20 UTC, ZavezX commented on source/coordinator/GreenEnergyHub.Aggregation.DatabaseMigration/Scripts/202108101448_Updates.sql
> +    ExecutionEnd DateTimeOffset NULL
We should add `ProcessVariant` here as well.

2021-08-12 08:20 UTC, ZavezX commented on source/coordinator/GreenEnergyHub.Aggregation.Domain/DTOs/MetaData/JobMetadata.cs
> +        public JobMetadata(JobProcessTypeEnum processType, Guid id, Interval processPeriod, JobTypeEnum jobType, string jobOwner, string gridArea)
We should add `ProcessVariant` to `JobMetaData` and make it nullable.

2021-08-12 08:20 UTC, ZavezX commented on source/coordinator/GreenEnergyHub.Aggregation.Domain/DTOs/MetaData/JobMetadata.cs
> +            GridArea = gridArea;
I'm not a fan of the `GridArea` naming here, as it could contain a string repsresentation of multiple grid areas. Maybe we should add another table to hold values of grid areas?

2021-08-12 08:20 UTC, ZavezX commented on source/coordinator/GreenEnergyHub.Aggregation.Domain/DTOs/MetaData/JobMetadata.cs
> +        public Instant ExecutionEnd { get; set; }
This should be nullable.

2021-08-12 08:20 UTC, ZavezX commented on source/coordinator/GreenEnergyHub.Aggregation.Domain/DTOs/MetaData/JobProcessTypeEnum.cs
> +        Wholesale = 1,
I don't think this is representative enough in regards to which processes we can have. In aggregation we have both D03 (Aggregation) and D04 (Balance Fixing). In Wholesale we have D05 (Wholesale Settlement) and D32 (Wholesale Fixing).

2021-08-12 08:20 UTC, ZavezX commented on source/coordinator/GreenEnergyHub.Aggregation.Domain/DTOs/MetaData/JobStateEnum.cs
> +        ClusterStartup = 1,
Is it possible that the code would ever stop working at `JobCreated`?

2021-08-12 08:20 UTC, ZavezX commented on source/coordinator/GreenEnergyHub.Aggregation.Domain/DTOs/MetaData/JobTypeEnum.cs
> +        Live = 1,
Do we expect to have more job types than these two? If not I would prefer to have this represented as and enum instead.

2021-08-12 08:20 UTC, ZavezX commented on source/coordinator/GreenEnergyHub.Aggregation.Infrastructure/MetaDataDataAccess.cs
> +                [ExecutionEnd]) VALUES
`ExecutionEnd` should not be part of `InsertJobAsync`.

2021-08-12 09:48 UTC, kristianschneider commented on source/coordinator/GreenEnergyHub.Aggregation.Coordinator/CoordinationTriggers.cs
> +            }
You can ultimatly control what areas you want to calculate on. As an operator you might want to calculate on a specific area.
in 
p.add('--grid-area', type=str, required=False, help='Run aggregation for specific grid areas format is { "areas": ["123","234"]}. If none is specifed. All grid areas are calculated')

2021-08-12 09:49 UTC, kristianschneider commented on source/coordinator/GreenEnergyHub.Aggregation.Domain/DTOs/MetaData/JobProcessTypeEnum.cs
> +        Wholesale = 1,
Then we'll extend once we get to it

2021-08-12 09:51 UTC, kristianschneider commented on source/coordinator/GreenEnergyHub.Aggregation.Infrastructure/MetaDataDataAccess.cs
> +                [ExecutionEnd]) VALUES
It is part of the description in the story :
Execution date (Start and end date)

You might want to be interested in seeing normal run times in the consuming UI so that you can predict how long a new run will take.

2021-08-12 12:46 UTC, ZavezX requested changes

2021-08-12 12:46 UTC, ZavezX commented on source/coordinator/GreenEnergyHub.Aggregation.Application/Coordinator/ICoordinatorService.cs
> +            string processVariant,
We don't need `procesVariant` for aggregation job, this is only relevant for wholesale job.

2021-08-12 12:46 UTC, ZavezX commented on source/coordinator/GreenEnergyHub.Aggregation.Coordinator/CoordinationTriggers.cs
> +            if (processVariantString == null)
`processVariant` should be nullable as only wholesale job uses it in case of job type wholesale settlement (D32).

2021-08-12 12:46 UTC, ZavezX commented on source/coordinator/GreenEnergyHub.Aggregation.DatabaseMigration/Scripts/202108111253_Updates.sql
> +	ProcessVariant nchar(255) NOT NULL DEFAULT ''
Should be nullable.

2021-08-12 12:46 UTC, ZavezX commented on source/coordinator/GreenEnergyHub.Aggregation.Domain/DTOs/MetaData/JobMetadata.cs
> +        public Instant ExecutionEnd { get; set; }
And only be set when job is finished.

2021-08-12 12:46 UTC, ZavezX commented on source/coordinator/GreenEnergyHub.Aggregation.Infrastructure/MetaDataDataAccess.cs
> +                [ExecutionEnd]) VALUES
But we have `ProcessPeriodStart` and `ProcessPeriodEnd` to reflect the period of the process. `Created` and `ExecutionEnd` reflects when it was started and when all the calculations are done. That's why it must be nullable and not inserted when the job meta data is created at first. Only when the job is finished, the `ExecutionEnd` should be filled out.

2021-08-13 07:45 UTC, ZavezX approved these changes

2021-08-13 08:43 UTC, merged