Poc/174 store basis data for wholesale
Energinet-DataHub/geh-aggregations pull request #257
Opened 2021-08-17 13:03 UTC by mknic

## Description

Use the same concepts for storing results when it comes to storing basis data for aggregation and wholesale.

- Use dictionary to contain basis data
- Rewrite `post processor` to take the dictionary and store data for each <key,value> pair in the dictionary
- Prepare for storing basis data for wholesale process. Depends on #167, #168 and #169

When all dependent issues has been solved a follow up PR will be created to make sure basis data are stored correctly for the wholesale process.

## References

* #174

2021-08-17 18:13 UTC, ZavezX requested changes

2021-08-17 18:13 UTC, ZavezX commented on source/databricks/geh_stream/aggregation_utils/trigger_base_arguments.py
>      p.add('--persist-source-dataframe-location', type=str, required=False, default="delta/basis-data/")
We don't save the basis data in delta format, would a better naming for the basis data path be relevant?

2021-08-17 18:13 UTC, ZavezX commented on source/databricks/geh_stream/shared/services/postprocessor.py
> +            print(path)
Print can be removed.

2021-08-17 18:13 UTC, ZavezX commented on source/databricks/geh_stream/shared/services/postprocessor.py
> +            snapshot_path = f"abfss://{args.data_storage_container_name}@{args.data_storage_account_name}.dfs.core.windows.net/{path}"
We use this formatting of a path many places in the code. This is a strong candidate for a shared function that can return this formatted path.

2021-08-17 18:13 UTC, ZavezX commented on source/databricks/geh_stream/shared/services/postprocessor.py
> +        for key, value in snapshot_data.items():
Would be more descriptive to use `key, dataframe`.

2021-08-17 18:13 UTC, ZavezX commented on source/databricks/geh_stream/shared/services/postprocessor.py
> +    def store_basis_data(self, args, snapshot_data):
Would be nice to add types to the function parameters.

2021-08-18 06:05 UTC, mknic commented on source/databricks/geh_stream/aggregation_utils/aggregators/aggregation_initializer.py
> +def get_time_series_dataframe(args, areas, spark, snapshot_data):
Very good input. I will make that change.

2021-08-18 06:06 UTC, mknic commented on source/databricks/aggregation-jobs/wholesale_trigger.py
> +snapshot_data["metering_points_df"] = metering_points
I need you to elaborate on this. I'm not sure I understand what you mean.

2021-08-18 06:09 UTC, mknic commented on source/databricks/geh_stream/aggregation_utils/trigger_base_arguments.py
>      p.add('--persist-source-dataframe-location', type=str, required=False, default="delta/basis-data/")
Agree but as we talked about yesterday I will create an issue to do the renaming. We have other arguments we want to rename and I would think we could save some time if we take the discussion about naming upfront before the implementation is started.

2021-08-18 06:11 UTC, mknic commented on source/databricks/geh_stream/shared/services/postprocessor.py
> +    def store_basis_data(self, args, snapshot_data):
Good idea!

2021-08-18 06:19 UTC, ZavezX commented on source/databricks/aggregation-jobs/wholesale_trigger.py
> +snapshot_data["metering_points_df"] = metering_points
The `snapshot_data` is a dictionary of `key, dataframe`. That means we can get the dataframe back by it's key from the dictionary. Therefor we don't need the variables for each dataframe as we already have them in the dictionary.

2021-08-18 06:19 UTC, mknic commented on source/databricks/geh_stream/shared/services/postprocessor.py
> +    def store_basis_data(self, args, snapshot_data):
I can see our codebase lacks of this convention having types in function parameters. Maybe we need an issue to handle it if we want it that way?

2021-08-18 12:00 UTC, ZavezX approved these changes
Looks good.

2021-08-19 05:45 UTC, johevemi approved these changes

2021-08-19 07:15 UTC, merged