WIP Task/268 snapshot
Energinet-DataHub/geh-aggregations pull request #294
Opened 2021-08-31 10:59 UTC by johevemi

## Description

## References

* #0000

2021-09-02 13:54 UTC, ZavezX requested changes

2021-09-02 13:54 UTC, ZavezX commented on source/coordinator/GreenEnergyHub.Aggregation.Application/Coordinator/CoordinatorService.cs
> +
These parameters could be moved to `GetTriggerPrepArguments` method.

2021-09-02 13:54 UTC, ZavezX commented on source/coordinator/GreenEnergyHub.Aggregation.Application/Coordinator/InputProcessor.cs
> +
```suggestion
```

2021-09-02 13:54 UTC, ZavezX commented on source/coordinator/GreenEnergyHub.Aggregation.Application/Coordinator/Interfaces/IMetaDataDataAccess.cs
> +        Task UpdateSnapshotPath(Guid snapshotId, string path);
Method name should reflect that it is async.

2021-09-02 13:54 UTC, ZavezX commented on source/coordinator/GreenEnergyHub.Aggregation.DatabaseMigration/GreenEnergyHub.Aggregation.DatabaseMigration.csproj
> +      <None Remove="Scripts\202109011100_DropExistingTablesAndInsertNewTables.sql" />
```suggestion
```

2021-09-02 19:59 UTC, mknic requested changes

2021-09-02 19:59 UTC, mknic commented on source/coordinator/GreenEnergyHub.Aggregation.Application/Coordinator/ITriggerBaseArguments.cs
> +        /// Returns base arguments used for databricks job trigger functions
```suggestion
        /// Returns arguments used for data preparation databricks job trigger function
```

2021-09-02 19:59 UTC, mknic commented on source/coordinator/GreenEnergyHub.Aggregation.Application/Coordinator/ITriggerBaseArguments.cs
> +        /// Returns base arguments used for databricks job trigger functions
The comment should reflect the new responsibility of the method. Something like the suggestion above. 

Is this used for triggering aggregation job only or is it triggering wholesale job as well?

2021-09-02 19:59 UTC, mknic commented on source/coordinator/GreenEnergyHub.Aggregation.Application/Coordinator/TriggerBaseArguments.cs
>                  $"--telemetry-instrumentation-key={_coordinatorSettings.TelemetryInstrumentationKey}",
Do we tend to use this after we have removed the deprecated telemetry python for python?

2021-09-02 19:59 UTC, mknic commented on source/coordinator/GreenEnergyHub.Aggregation.Application/Coordinator/ITriggerBaseArguments.cs
> +        List<string> GetTriggerPrepArguments(Instant fromDate, Instant toDate, string gridAreas, JobProcessTypeEnum processType, Guid jobId, Guid snapshotId);
Could we stick to the naming convention `...DataPreparation...` for the new job, trigger etc. we have introduced?

2021-09-02 19:59 UTC, mknic commented on source/coordinator/GreenEnergyHub.Aggregation.DatabaseMigration/Scripts/202109011100_DropExistingTablesAndInsertNewTables.sql
> +    [FromDate] DATETIME2(7) NOT NULL,
just for curiosity. How did we end in 7 in the decimal seconds precision?

2021-09-03 05:36 UTC, johevemi commented on source/coordinator/GreenEnergyHub.Aggregation.DatabaseMigration/Scripts/202109011100_DropExistingTablesAndInsertNewTables.sql
> +    [FromDate] DATETIME2(7) NOT NULL,
datetime2 [ (fractional seconds precision) ] it the default in the [documentation from microsoft ](https://docs.microsoft.com/en-us/sql/t-sql/data-types/datetime2-transact-sql?view=sql-server-ver15)
we can change it to whatever depending on how precise we need to be, which i do not know

2021-09-03 05:46 UTC, johevemi commented on source/coordinator/GreenEnergyHub.Aggregation.Application/Coordinator/TriggerBaseArguments.cs
>                  $"--telemetry-instrumentation-key={_coordinatorSettings.TelemetryInstrumentationKey}",
no idea

2021-09-03 05:59 UTC, johevemi commented on source/coordinator/GreenEnergyHub.Aggregation.Application/Coordinator/CoordinatorService.cs
> +
Moved to GetTriggerPrepArguments, but now that i look it through should these 3 parameters not be added to a GetTriggerWholesaleArguments which is also missing, instead?

2021-09-03 06:04 UTC, johevemi commented on source/coordinator/GreenEnergyHub.Aggregation.Application/Coordinator/ITriggerBaseArguments.cs
> +        /// Returns base arguments used for databricks job trigger functions
I see the confusion. Yes the summary should reflect the correct responsibilities, but i believe that there is missing a GetTriggerWholesaleArguments that contains charges, charges-links and charge-prices, which is currently in the GetTriggerDataPreparationArguments.

2021-09-03 06:16 UTC, johevemi commented on source/coordinator/GreenEnergyHub.Aggregation.Application/Coordinator/ITriggerBaseArguments.cs
> +        /// Returns base arguments used for databricks job trigger functions
But I am not sure if charges, charges-links and charge-prices should stay in GetTriggerDataPreparationArguments since it is cosmos container

2021-09-03 06:22 UTC, johevemi commented on source/coordinator/GreenEnergyHub.Aggregation.Application/Coordinator/TriggerBaseArguments.cs
> +                $"--cosmos-container-charges={_coordinatorSettings.CosmosContainerCharges}",
Should charges, charge-links and charge-prices be in GetTriggerDataPreparationArguments or GetTriggerWholesaleArguments?

2021-09-03 06:24 UTC, johevemi commented on source/coordinator/GreenEnergyHub.Aggregation.Application/Coordinator/CoordinatorService.cs
> +
I have created a comment on the [question ](https://github.com/Energinet-DataHub/geh-aggregations/pull/294#discussion_r701614449)

2021-09-03 06:51 UTC, johevemi commented on source/coordinator/GreenEnergyHub.Aggregation.Application/Coordinator/TriggerBaseArguments.cs
> +                $"--cosmos-container-charges={_coordinatorSettings.CosmosContainerCharges}",
In GetTriggerDataPreparationArguments

2021-09-03 06:58 UTC, johevemi commented on source/coordinator/GreenEnergyHub.Aggregation.Application/Coordinator/ITriggerBaseArguments.cs
> +        /// Returns base arguments used for databricks job trigger functions
should stay in GetTriggerDataPreparationArguments

2021-09-03 07:09 UTC, johevemi commented on source/coordinator/GreenEnergyHub.Aggregation.Application/Coordinator/TriggerBaseArguments.cs
>                  $"--telemetry-instrumentation-key={_coordinatorSettings.TelemetryInstrumentationKey}",
we will introduce telemetry eventually in python code and we will probably use the same telemetry instrumentation key

2021-09-03 07:20 UTC, mknic approved these changes

2021-09-06 12:26 UTC, ZavezX approved these changes

2021-09-06 12:27 UTC, merged