WIP Preparation job
Energinet-DataHub/geh-aggregations pull request #296
Opened 2021-09-01 10:24 UTC by kristianschneider

This PR separates the ingestion of data out of the aggregation and wholesale job.
Input data is now stored as a snapshot and used in the following jobs.

2021-09-01 13:09 UTC, ZavezX requested changes

2021-09-01 13:09 UTC, ZavezX commented on source/databricks/aggregation-jobs/preparation_trigger.py
> +    initialize_spark
We should use the shared `data_loader` instead.

2021-09-02 07:50 UTC, johevemi commented
need snapshotId

2021-09-02 07:52 UTC, johevemi commented on source/databricks/geh_stream/shared/services/coordinator_service.py
> -        self.snapshot_url = args.snapshot_url
Needs a snapshotId

2021-09-02 07:58 UTC, johevemi commented on source/databricks/geh_stream/shared/services/coordinator_service.py
>          self.result_id = args.result_id
We also need a snapshotId in the header https://github.com/Energinet-DataHub/geh-aggregations/blob/2f7de5d85daf989dcc9a393b759ef8266383442e/source/databricks/geh_stream/shared/services/coordinator_service.py#L33 for the snapshotReciver in the dotnet code for us to update the path on a given snapshot

2021-09-07 11:47 UTC, kristianschneider commented on source/databricks/geh_stream/shared/services/coordinator_service.py
>          self.result_id = args.result_id
done

2021-09-07 11:49 UTC, johevemi approved these changes

2021-09-07 12:17 UTC, ZavezX requested changes
Arguments sent from the coordinator functions have changed. 
[trigger_base_arguments](https://github.com/Energinet-DataHub/geh-aggregations/blob/c96dccbb4211c8d0cacec6ec6e24922105bd381c/source/databricks/geh_stream/aggregation_utils/trigger_base_arguments.py) needs to be updated to correspond to the arguments sent from [here](https://github.com/Energinet-DataHub/geh-aggregations/blob/c96dccbb4211c8d0cacec6ec6e24922105bd381c/source/coordinator/GreenEnergyHub.Aggregation.Coordinator/CoordinationTriggers.cs#L319), [here](https://github.com/Energinet-DataHub/geh-aggregations/blob/c96dccbb4211c8d0cacec6ec6e24922105bd381c/source/coordinator/GreenEnergyHub.Aggregation.Coordinator/CoordinationTriggers.cs#L356) and [here](https://github.com/Energinet-DataHub/geh-aggregations/blob/c96dccbb4211c8d0cacec6ec6e24922105bd381c/source/coordinator/GreenEnergyHub.Aggregation.Coordinator/CoordinationTriggers.cs#L294)

2021-09-08 08:19 UTC, ZavezX approved these changes

2021-09-08 08:20 UTC, merged