Feature/268 fix result receiver
Energinet-DataHub/geh-aggregations pull request #312
Opened 2021-09-08 13:36 UTC by ZavezX

## Description

- Outcomment result processing from result receiver.
- Save results to database.

## References

* #268

2021-09-08 19:01 UTC, mknic requested changes
Looks good. Just a small renaming of `GetJob`

2021-09-08 19:01 UTC, mknic commented on source/coordinator/GreenEnergyHub.Aggregation.Application/Coordinator/CoordinatorService.cs
> +            return await _metaDataDataAccess.GetJob(jobId);
```suggestion
            return await _metaDataDataAccess.GetJobAsync(jobId);
```

2021-09-08 19:01 UTC, mknic commented on source/coordinator/GreenEnergyHub.Aggregation.Coordinator/CoordinationTriggers.cs
> +                // var job = await _coordinatorService.GetJob(jobId).ConfigureAwait(false);
```suggestion
                // var job = await _coordinatorService.GetJobAsync(jobId).ConfigureAwait(false);
```

2021-09-13 12:43 UTC, kristianschneider approved these changes

2021-09-13 12:43 UTC, johevemi approved these changes

2021-09-13 13:08 UTC, mknic approved these changes

2021-09-13 13:44 UTC, merged