WIP Story 346 unittest for fees and subscriptions
Energinet-DataHub/geh-aggregations pull request #368
Opened 2021-09-21 13:26 UTC by johevemi

## Description
Split subscription and fee calculator methods op into small more testable methods and create unit test for those methods 

## References

* #346

2021-09-23 10:59 UTC, jonasdmoeller approved these changes

2021-09-23 11:20 UTC, mknic requested changes
Very nice work. Besides a small typo in multiple places it looks good.

2021-09-23 11:20 UTC, mknic commented on source/databricks/tests/wholesale_utils/calculators/test_fee_calculators.py
> +charges_flex_settled_consumption_dataset_1 = [("chargea-D01-001", "chargea", "D01", "001", Decimal("100.10"), datetime(2020, 1, 1, 0, 0), "E17", "D01", "chargea", 1, 1)]
small typo in `chargea...`. should be `charges...`. I think it's applicable to more of the tests.

2021-09-23 11:20 UTC, mknic commented on source/databricks/tests/wholesale_utils/calculators/test_subscription_calculators.py
> +subscription_charges_dataset_1 = [("chargea-D01-001", "chargea", "D01", "001", Decimal("200.50"), datetime(2020, 1, 1, 0, 0), "E17", "D01", "chargea", 1, 1)]
same issue here

2021-09-23 11:20 UTC, mknic commented on source/databricks/tests/wholesale_utils/calculators/test_subscription_calculators.py
> +charges_flex_settled_consumption_dataset_1 = [("chargea-D01-001", "chargea", "D01", "001", Decimal("100.10"), datetime(2020, 1, 1, 0, 0), "E17", "D01", "chargea", 1, 1)]
another one. a search and replace will fix it I guess :-)

2021-09-23 12:31 UTC, johevemi commented on source/databricks/tests/wholesale_utils/calculators/test_fee_calculators.py
> +charges_flex_settled_consumption_dataset_1 = [("chargea-D01-001", "chargea", "D01", "001", Decimal("100.10"), datetime(2020, 1, 1, 0, 0), "E17", "D01", "chargea", 1, 1)]
It is actually not a typo but is meant to be read as "charge a, charge b, charge c" to create a charge_id. But I see your point and will change it to "001" or something like that

2021-09-24 08:57 UTC, ZavezX approved these changes
Just a little thought, otherwise it looks good.

2021-09-24 08:57 UTC, ZavezX commented on source/databricks/tests/helpers/dataframe_defaults.py
> +const_charge_type = ChargeType.subscription
Why set default charge type? Isn't it supposed to be used for all types of charges?

2021-09-24 09:12 UTC, merged