WIP Feature/401 change schema of aggregation results
Energinet-DataHub/geh-aggregations pull request #466
Opened 2021-11-03 07:06 UTC by johevemi

## Description

## References

* #401

2021-11-03 11:52 UTC, kristianschneider approved these changes

2021-11-04 08:20 UTC, mknic requested changes
Nice work and great improvements!

2021-11-04 08:20 UTC, mknic commented on source/databricks/geh_stream/aggregation_utils/aggregation_result_creator.py
> +def create_dataframe_from_aggregation_result_schema(metadata, result) -> DataFrame:
it would be nice to have data types on arguments as well.

2021-11-04 08:20 UTC, mknic commented on source/databricks/geh_stream/aggregation_utils/aggregation_result_creator.py
> +    result = result.na.fill(value=0, subset=[Colname.sum_quantity])
it would be nice with a code comment eg. "replace none values with zero"

2021-11-04 08:20 UTC, mknic commented on source/databricks/tests/aggregation_utils/aggregators/test_added_grid_loss.py
> +def test_returns_correct_schema(agg_result_factory):
data type on argument would be great here. 

It might be a huge task to add arguments on all method arguments and return types but it would be nice if you would do it in methods etc. you've added in this PR.

2021-11-04 08:20 UTC, mknic commented on source/databricks/tests/aggregation_utils/aggregators/test_added_system_correction.py
> +def test_returns_correct_schema(agg_result_factory):
data type on argument here as well

2021-11-04 08:20 UTC, mknic commented on source/databricks/tests/aggregation_utils/aggregators/test_flex_consumption.py
> +from pyspark.sql.types import NullType, StructType, StringType, DecimalType, TimestampType
is `NullType` used anywhere?

2021-11-04 08:20 UTC, mknic commented on source/databricks/tests/aggregation_utils/aggregators/test_flex_consumption_ga_brp_es.py
> +def test_returns_correct_schema(time_series_row_factory):
data type on argument here as well

2021-11-04 08:20 UTC, mknic commented on source/databricks/tests/aggregation_utils/aggregators/test_hourly_consumption_ga_brp_es.py
> +def test_hourly_consumption_supplier_aggregator_returns_correct_schema(time_series_row_factory):
data type on argument here as well

2021-11-05 08:19 UTC, johevemi commented on source/databricks/tests/aggregation_utils/aggregators/test_added_grid_loss.py
> +def test_returns_correct_schema(agg_result_factory):
we will look into this at a later date

2021-11-05 12:10 UTC, mknic approved these changes

2021-11-05 12:12 UTC, merged