458 common update logic
Energinet-DataHub/geh-aggregations pull request #468
Opened 2021-11-03 09:17 UTC by kristianschneider

This PR implements a common handler for creating and mutating periods on masterdata.
There are associated unit tests in /tests/streaming/test_metering_point_dispatcher.py

* #458

2021-11-03 13:34 UTC, mknic requested changes
It looks good and I really like the way we can call a single method in all update handlers.

I have a general suggestion for the names of the test methods. @johevemi introduced a naming standard with the following structure: 

`test__<name of method to test>__<expected output>`

I really like that convention and think we should consider using it here as well. I used it in #464  as well.

2021-11-03 13:34 UTC, mknic commented on source/databricks/tests/streaming/test_metering_point_dispatcher.py
> +def test_changed_period_after_update(spark):
it would be nice to make it explicit that this is about update of an existing period

2021-11-03 13:34 UTC, mknic commented on source/databricks/geh_stream/bus/messages/meteringpoint.py
>              datetime(9999, 1, 1, 0, 0))]
do we need to verify if this is the best way to set the max date?

2021-11-03 13:34 UTC, mknic commented on source/databricks/geh_stream/bus/messages/meteringpoint.py
> +            "",  # out_grid_area
should we consider using `None`/`Null` instead of empty string?

2021-11-08 09:26 UTC, ZavezX requested changes

2021-11-09 08:20 UTC, ZavezX commented on source/databricks/tests/streaming/test_metering_point_dispatcher.py
> +#   to_date
Let's just keep them and rewrite unit tests in another issue.

2021-11-09 08:21 UTC, ZavezX commented on source/databricks/tests/streaming/test_metering_point_dispatcher.py
> +def test_changed_period_after_update(spark):
Again let's rewrite unit tests in another issue.

2021-11-09 09:43 UTC, ZavezX commented on source/databricks/geh_stream/bus/messages/meteringpoint.py
>              datetime(9999, 1, 1, 0, 0))]
Let's stick with this for now.

2021-11-10 07:05 UTC, ZavezX approved these changes

2021-11-10 19:02 UTC, mknic requested changes
@ZavezX do we need to extend the unit test suite before we can close this PR?

2021-11-10 19:02 UTC, mknic commented on source/databricks/tests/streaming/test_metering_point_dispatcher.py
> +# def test_multiple_properties_updated_in_exsisting_period(spark):
@ZavezX what to do with this?

2021-11-11 11:26 UTC, ZavezX commented
> @ZavezX do we need to extend the unit test suite before we can close this PR?

I think we should take care of unit tests in another issue and get this rolling to begin testing the solution.

2021-11-11 11:34 UTC, mknic approved these changes

2021-11-11 11:34 UTC, merged