Feature/476 metering point connected
Energinet-DataHub/geh-aggregations pull request #495
Opened 2021-11-16 09:31 UTC by ZavezX

## Description

### .NET

- Refactor existing method to parse ServiceBus metadata to `EventMetadata` object with added properties stated in [ADR-0008](https://github.com/Energinet-DataHub/green-energy-hub/blob/main/docs/architecture-decision-record/ADR-0008%20Integration%20events.md)
- Add common method to construct `EventHubMetadata` dictionary
- Add unit tests for added functionality surrounding parsing of ServiceBus meta data
- Change internal meta data for EventHub to include more values to be used in python part

### Python

- Add `MeteringPointConnected` class to be able to update existing periods for MeteringPoint
- Add unit tests for `period_mutation` functions
- Refactor columns for `Events` table corresponding to changes in .Net part for internal EventHub meta data

## References

* #476 
* #317

2021-11-19 06:55 UTC, johevemi approved these changes

2021-11-22 13:23 UTC, jonasdmoeller requested changes

2021-11-22 13:23 UTC, jonasdmoeller commented on source/IntegrationEventListener/source/Energinet.DataHub.Aggregations.Application/Extensions/EnumExtension.cs
> +        public static string GetDescription(this Enum enumValue)
If we use an enum for ConnectionState in MeteringPointConnectedEvent, this should not be necessary as we use custom converters for the json serialization.

2021-11-22 13:23 UTC, jonasdmoeller commented on source/databricks/geh_stream/streaming_utils/eventhub_ingestor.py
> +            (df.properties["domain"].alias("domain")),
Maybe we should move these json property names to a constant, as they are use several places.

2021-11-22 13:23 UTC, jonasdmoeller commented on source/databricks/geh_stream/streaming_utils/eventhub_ingestor.py
> +            .partitionBy("event_name") \
Same as previous comment

2021-11-22 13:23 UTC, jonasdmoeller commented on source/databricks/geh_stream/streaming_utils/events_data_lake_listener.py
> +            event_class = message_registry.get(row["event_name"])
Same as previous comment

2021-11-22 13:33 UTC, mknic commented on source/IntegrationEventListener/source/Energinet.DataHub.Aggregations.Domain/ConnectionState.cs
> +        [Description("D03")]
It's necessary as we use the `Description` as the value on the python side of it. @ZavezX might be able to elaborate on this.

2021-11-22 13:35 UTC, mknic commented on source/IntegrationEventListener/source/Energinet.DataHub.Aggregations.Application/IntegrationEvents/MeteringPoints/MeteringPointConnectedEvent.cs
> +            string ConnectionState,
I thought we agreed on using strings in our internal contract?

2021-11-22 13:35 UTC, mknic commented on source/databricks/geh_stream/streaming_utils/eventhub_ingestor.py
> +            (df.properties["domain"].alias("domain")),
Good idea!

2021-11-22 14:05 UTC, ZavezX commented on source/IntegrationEventListener/source/Energinet.DataHub.Aggregations.Domain/ConnectionState.cs
> +        [Description("D03")]
The `Description` attribute is meant to be used to hold the business value, thus we as developers don't need to remember all the different codes, instead we can just extract it from the attribute.

2021-11-22 14:07 UTC, ZavezX commented on source/IntegrationEventListener/source/Energinet.DataHub.Aggregations.Application/IntegrationEvents/MeteringPoints/MeteringPointConnectedEvent.cs
> +            string ConnectionState,
I also remember we agreed to use string for ConnectionString in our internal event model.

2021-11-22 14:11 UTC, ZavezX commented on source/IntegrationEventListener/source/Energinet.DataHub.Aggregations.Application/Extensions/EnumExtension.cs
> +        public static string GetDescription(this Enum enumValue)
We use the `Description` attribute directly in the mapper for `MeteringPointConnected`, so we don't need to do custom json serialization as the `ConnectionState` property is a string.

2021-11-24 07:27 UTC, jonasdmoeller commented on source/IntegrationEventListener/source/Energinet.DataHub.Aggregations.Application/IntegrationEvents/MeteringPoints/MeteringPointConnectedEvent.cs
> +            string ConnectionState,
We did agree on using strings in our internal contract. And using custom converters in the JsonSerializer we convert these enums to strings in a strongly typed manner, and thus preventing an invalid event being transfered through our ingestion layer.
If we still decide to use string properties in the event model, we should refactor the ConsumptionMeteringPointCreatedEvent to do the same.

2021-11-24 07:27 UTC, jonasdmoeller commented on source/IntegrationEventListener/source/Energinet.DataHub.Aggregations.Domain/ConnectionState.cs
> +        [Description("D03")]
See comment below

2021-11-24 07:28 UTC, jonasdmoeller commented on source/IntegrationEventListener/source/Energinet.DataHub.Aggregations.Application/Extensions/EnumExtension.cs
> +        public static string GetDescription(this Enum enumValue)
See comment above

2021-11-24 13:18 UTC, jonasdmoeller approved these changes

2021-11-24 13:18 UTC, merged