WIP Feature/348 create cim xml for grid company
Energinet-DataHub/geh-aggregations pull request #503
Opened 2021-11-19 07:02 UTC by johevemi

## Description

![image](https://user-images.githubusercontent.com/39729843/142579088-dcf59075-db6f-4e91-9f53-14d67d808541.png)
A new project that converts the results from a aggregation process run in databricks to CIM XML.

## References

* #348

2021-11-26 08:32 UTC, mknic submitted a review, later dismissed

2021-11-26 08:32 UTC, mknic commented on source/AggregationResultReceiver/source/AggregationResultReceiver.Tests/Converters/CimXmlConverterTests.cs
> +                "result_mock_total_consumption.json",
could be moved to an enum, static class or similar

2021-11-26 08:32 UTC, mknic commented on source/AggregationResultReceiver/source/AggregationResultReceiver.Tests/TestHelpers/AutoMoqDataAttribute.cs
> +    public class AutoMoqDataAttribute : AutoDataAttribute
could we add a comment as to why this is needed?

2021-11-26 08:40 UTC, johevemi commented on source/AggregationResultReceiver/source/AggregationResultReceiver.Application/Helpers/IGuidGenerator.cs
> +        public string GetGuid();
It is string because we don't want dashes (-) in our mRID so we use .toString("N") to only select digits.
We could create an extension for it.

2021-11-26 08:41 UTC, johevemi commented on source/AggregationResultReceiver/source/AggregationResultReceiver.Infrastructure/Converters/CimXmlConverter.cs
> +            // list.Add(ResultGroupingDDQ(results));
I will add TODO on them, since we need to implement them at a later date

2021-11-26 08:53 UTC, johevemi commented on source/AggregationResultReceiver/source/AggregationResultReceiver.Tests/TestHelpers/AutoMoqDataAttribute.cs
> +    public class AutoMoqDataAttribute : AutoDataAttribute
yes

2021-11-26 09:00 UTC, johevemi commented on source/AggregationResultReceiver/source/AggregationResultReceiver.Infrastructure/Converters/CimXmlConverter.cs
> +                cimNamespace + CimXmlConstants.Period,
adding string interpolation or string.format will just add more code. But if we think this should be done I have no problem with it.

2021-11-26 09:08 UTC, johevemi commented on source/AggregationResultReceiver/source/AggregationResultReceiver.Infrastructure/Storage/FileStore.cs
> +            await _aggregationResultsBlobStorage.UploadBlobAsync(fileName, content, CancellationToken.None).ConfigureAwait(false);
No, it is not supposed to return anything, tho you could argue that it should return a message if the content has been uploaded or not.

2021-11-26 10:20 UTC, johevemi commented on source/AggregationResultReceiver/source/AggregationResultReceiver.Tests/Converters/CimXmlConverterTests.cs
> +                "result_mock_total_consumption.json",
I am not sure why this should be moved

2021-11-26 10:21 UTC, johevemi commented on source/AggregationResultReceiver/source/AggregationResultReceiver.IntegrationTests/Fixtures/AggregationsFunctionAppFixture.cs
> +        public TopicResource? JobCompletedTopic { get; private set; }
@jonasdmoeller can you take a look at this?

2021-11-29 08:49 UTC, ZavezX requested changes

2021-11-29 08:49 UTC, ZavezX commented on source/AggregationResultReceiver/source/AggregationResultReceiver.Infrastructure/Converters/CimXmlConverter.cs
> +                        "2021-09-05T22:00Z"),
Shouldn't we use a value from the `result` here to set the `TimeIntervalStart` instead of hard coding a value?

2021-11-29 08:49 UTC, ZavezX commented on source/AggregationResultReceiver/source/AggregationResultReceiver.Infrastructure/Converters/CimXmlConverter.cs
> +                        "2221-09-06T22:00Z")),
Shouldn't we use a value from the `result` here to set the `TimeIntervalEnd instead of hard coding a value?

2021-11-29 08:49 UTC, ZavezX commented on source/AggregationResultReceiver/source/AggregationResultReceiver.Infrastructure/Converters/CimXmlConverter.cs
> +                        "E31"), // const
What he said👆

2021-11-29 08:49 UTC, ZavezX commented on source/AggregationResultReceiver/source/AggregationResultReceiver.Infrastructure/Converters/CimXmlConverter.cs
> +                        "E31"), // const
And that goes for all the magic string values in general.

2021-11-29 08:49 UTC, ZavezX commented on source/AggregationResultReceiver/source/AggregationResultReceiver.Infrastructure/Helpers/GuidGenerator.cs
> +        }
What is the purpose for this method? Could you explain?

2021-11-29 08:49 UTC, ZavezX commented on source/AggregationResultReceiver/source/AggregationResultReceiver.Infrastructure/Serialization/JsonSerializerNamingPolicy.cs
> +}
Is this used anywhere now that we use the `SnakeCaseNamingStrategy` from Newtonsoft?

2021-11-29 08:49 UTC, ZavezX commented on source/AggregationResultReceiver/source/AggregationResultReceiver.Tests/Assets/ExpectedAggregationResultForPerGridAreaMdr501.xml.blob
> +        <cim:end>2221-09-06T22:00Z</cim:end>
This must be wrong time interval, look at the year...

2021-11-29 08:49 UTC, ZavezX commented on source/AggregationResultReceiver/source/AggregationResultReceiver.Tests/Assets/ExpectedAggregationResultForPerGridAreaMdr502.xml.blob
> +        <cim:end>2221-09-06T22:00Z</cim:end>
Same as above mentioned interval.

2021-11-29 08:54 UTC, johevemi commented on source/AggregationResultReceiver/source/AggregationResultReceiver.Application/IFileStore.cs
> +        Task<Stream> DownloadAggregationResultAsync(string fileName);
Name changed

2021-11-29 09:03 UTC, johevemi commented on source/AggregationResultReceiver/source/AggregationResultReceiver.Infrastructure/Converters/CimXmlConverter.cs
> +                        "2021-09-05T22:00Z"),
No such thing as TimeIntervalStart do you mean StartDateTime?

2021-11-29 09:04 UTC, johevemi commented on source/AggregationResultReceiver/source/AggregationResultReceiver.Infrastructure/Converters/CimXmlConverter.cs
> +                        "2221-09-06T22:00Z")),
No such thing as TimeIntervalEnd do you mean EndDateTime?

2021-11-29 09:07 UTC, johevemi commented on source/AggregationResultReceiver/source/AggregationResultReceiver.Infrastructure/Helpers/GuidGenerator.cs
> +        }
mRID needs to be a unique id, but it can not have dashes "-" in it, so we call ToString("N") to only select digits.

2021-11-29 09:15 UTC, johevemi commented on source/AggregationResultReceiver/source/AggregationResultReceiver.Infrastructure/Serialization/JsonSerializerNamingPolicy.cs
> +}
SnakeCaseNamingStrategy only works with Newtonsoft and we only use Newtonsoft in DeserializeStream method. JsonNamingPolicy is used then deserializing jobCompletedEvent. Some of the names could be removed since Newtonsoft handles deserialization of ResultData

2021-11-29 09:19 UTC, johevemi commented on source/AggregationResultReceiver/source/AggregationResultReceiver.Tests/Assets/ExpectedAggregationResultForPerGridAreaMdr502.xml.blob
> +        <cim:end>2221-09-06T22:00Z</cim:end>
It does not matter, it fits the hardcoded value in CimXmlConverter. It will be changed if the hardcoded values get changed

2021-11-29 09:24 UTC, johevemi commented on source/AggregationResultReceiver/source/AggregationResultReceiver.Infrastructure/Converters/CimXmlConverter.cs
> +        }
There is no reason to use grouping from JobCompleted. Grouping should be removed

2021-11-29 09:24 UTC, ZavezX commented on source/AggregationResultReceiver/source/AggregationResultReceiver.Infrastructure/Converters/CimXmlConverter.cs
> +                        "2221-09-06T22:00Z")),
If you look at the `CimXmlConstants.TimeIntervalEnd` it's stated right there. My question is if this value should come from the result object instead of hard coding it.

2021-11-29 09:25 UTC, ZavezX commented on source/AggregationResultReceiver/source/AggregationResultReceiver.Infrastructure/Helpers/GuidGenerator.cs
> +        }
Okay, good explanation.

2021-11-29 09:25 UTC, ZavezX commented on source/AggregationResultReceiver/source/AggregationResultReceiver.Infrastructure/Converters/CimXmlConverter.cs
> +                        "2021-09-05T22:00Z"),
If you look at the `CimXmlConstants.TimeIntervalStart` it's stated right there. My question is if this value should come from the result object instead of hard coding it.

2021-11-29 09:26 UTC, johevemi commented on source/AggregationResultReceiver/source/AggregationResultReceiver.Infrastructure/Converters/CimXmlConverter.cs
> +                        "2221-09-06T22:00Z")),
ResultData has no TimeIntervalEnd.  It has EndDateTime

2021-11-29 09:27 UTC, ZavezX commented on source/AggregationResultReceiver/source/AggregationResultReceiver.Infrastructure/Converters/CimXmlConverter.cs
> +        }
My point is that if we use some sort of grouping in the database we would not need to be explicit on the result names here, but I will let it be up to you to decide which solution works best.

2021-11-29 09:27 UTC, johevemi commented on source/AggregationResultReceiver/source/AggregationResultReceiver.Tests/Assets/ExpectedAggregationResultForPerGridAreaMdr501.xml.blob
> +        <cim:end>2221-09-06T22:00Z</cim:end>
It does not matter, it fits the hardcoded value in CimXmlConverter. It will be changed if the hardcoded values get changed

2021-11-29 10:01 UTC, johevemi commented on source/AggregationResultReceiver/source/AggregationResultReceiver.Infrastructure/Helpers/GuidGenerator.cs
> +    public class GuidGenerator : IGuidGenerator
Why. I need the interface to mock the output

2021-11-29 10:01 UTC, johevemi commented on source/AggregationResultReceiver/source/AggregationResultReceiver.Infrastructure/Helpers/InstantGenerator.cs
> +    public class InstantGenerator : IInstantGenerator
Why. I need the interface to mock the output

2021-11-30 08:04 UTC, johevemi commented
This PR will be completed after minor corrections from comments have been changed. Any bigger corrections or additional functionality will be split out into small stories and estimated accordingly.

2021-11-30 08:22 UTC, johevemi commented on source/AggregationResultReceiver/source/AggregationResultReceiver.Infrastructure/Converters/CimXmlConverter.cs
> +                        "2221-09-06T22:00Z")),
get EndDate from JobCompletedEvent

2021-11-30 08:23 UTC, johevemi commented on source/AggregationResultReceiver/source/AggregationResultReceiver.Infrastructure/Converters/CimXmlConverter.cs
> +                        "2021-09-05T22:00Z"),
get FromDate from JobCompletedEvent

2021-11-30 08:24 UTC, johevemi commented on source/AggregationResultReceiver/source/AggregationResultReceiver.Infrastructure/Converters/CimXmlConverter.cs
> +                        "2021-09-05T22:00Z"),
get FromDate from JobCompletedEvent

2021-11-30 08:25 UTC, johevemi commented on source/AggregationResultReceiver/source/AggregationResultReceiver.Infrastructure/Converters/CimXmlConverter.cs
> +        }
Might be changed in another story

2021-11-30 08:27 UTC, johevemi commented on source/AggregationResultReceiver/source/AggregationResultReceiver.Infrastructure/Helpers/GuidGenerator.cs
> +    public class GuidGenerator : IGuidGenerator
hardcoded constants will be handled in another story

2021-11-30 08:27 UTC, johevemi commented on source/AggregationResultReceiver/source/AggregationResultReceiver.Infrastructure/Converters/CimXmlConverter.cs
> +                        "E31"), // const
hardcoded constants will be handled in another story

2021-11-30 08:34 UTC, johevemi commented on source/AggregationResultReceiver/source/AggregationResultReceiver.Domain/ResultData.cs
> +        decimal SumQuantity,
yes

2021-11-30 11:07 UTC, jonasdmoeller commented on source/AggregationResultReceiver/source/AggregationResultReceiver.Domain/Enums/Grouping.cs
> +    }
Lets just go with string properties for now and create tasks for introducing protobuf between coordinator and result receiver

2021-11-30 11:07 UTC, jonasdmoeller approved these changes

2021-11-30 12:21 UTC, ZavezX approved these changes

2021-11-30 13:44 UTC, merged

2021-11-30 13:49 UTC, jonasdmoeller commented on source/AggregationResultReceiver/source/AggregationResultReceiver.IntegrationTests/Fixtures/AggregationsFunctionAppFixture.cs
> +        public TopicResource? JobCompletedTopic { get; private set; }
Godt set Morten, den property bliver initializeret i base class og må derfor gerne være null.