Feature/498 terraform fix integration event listener
Energinet-DataHub/geh-aggregations pull request #504
Opened 2021-11-19 12:25 UTC by ZavezX

## Description

- Use event hub sender connection string

## References

* #498

2021-11-22 12:17 UTC, mknic approved these changes
LGTM

2021-11-22 13:28 UTC, jonasdmoeller requested changes

2021-11-22 13:28 UTC, jonasdmoeller commented on .github/workflows/infrastructure-cd.yml
> +        id: myGetSecretAction
"myGetSecretAction" is not a good name. Maybe "aggregationGetSecretAction" is better?

2021-11-22 14:02 UTC, ZavezX commented on .github/workflows/infrastructure-cd.yml
> +          secrets: 'aggregation-evh-listening-key,aggregation-evh-sender-key'  # comma separated list of secret keys that need to be fetched from the Key Vault
```suggestion
          secrets: 'aggregation-evh-listening-key'  # comma separated list of secret keys that need to be fetched from the Key Vault 
```

2021-11-22 14:04 UTC, ZavezX commented on .github/workflows/infrastructure-cd.yml
> +        id: myGetSecretAction
The section is taken dircetly from an example online, but I did not add it, I only changed the position in the file. Let's just keep the naming as is.

2021-11-24 07:37 UTC, johevemi approved these changes

2021-11-24 07:38 UTC, jonasdmoeller approved these changes

2021-11-24 12:17 UTC, merged