Feature/514 manage const values in cim xml converter
Energinet-DataHub/geh-aggregations pull request #516
Opened 2021-12-01 12:28 UTC by johevemi

## Description

Manage const values in the converter.

## References

* #0000

2021-12-01 13:05 UTC, ZavezX approved these changes

2021-12-03 08:11 UTC, jonasdmoeller requested changes

2021-12-03 08:11 UTC, jonasdmoeller commented on source/AggregationResultReceiver/source/AggregationResultReceiver.Application/Converters/ICimXmlConverter.cs
> +    /// Interface for CimXmlConverter
The summary should describe what the interface is doing. The actual implementation is just a detail for users of the interface.
I.e. "Interface for converting list of aggregation results to CIM/XML documents"

2021-12-03 08:11 UTC, jonasdmoeller commented on source/AggregationResultReceiver/source/AggregationResultReceiver.Application/Helpers/IGuidGenerator.cs
>          public string GetGuidAsStringOnlyDigits();
If method is creating a new guid, the maybe name it CreateGuidAs....

2021-12-03 08:11 UTC, jonasdmoeller commented on source/AggregationResultReceiver/source/AggregationResultReceiver.Application/IFileStore.cs
> +        /// Upload stream to blob store at given blob name
The interface does not know about the implementation, so mentioning "blob store" in this context is not right. We could make a SqlFileStore implementation of the interface as well. Then the description would be wrong.

2021-12-03 08:11 UTC, jonasdmoeller commented on source/AggregationResultReceiver/source/AggregationResultReceiver.Application/IFileStore.cs
> +        /// Download stream from blob store with given blob name
Same as above

2021-12-03 13:19 UTC, jonasdmoeller approved these changes

2021-12-06 19:18 UTC, merged