Fixed log messages in function flow
Energinet-DataHub/geh-aggregations pull request #518
Opened 2021-12-02 14:36 UTC by jonasdmoeller

## Description

Fixing integration tests for IntegrationEventListener project.

## References

* #0000

2021-12-03 07:18 UTC, johevemi approved these changes

2021-12-03 07:46 UTC, ZavezX requested changes

2021-12-03 07:46 UTC, ZavezX commented on source/IntegrationEventListener/source/Energinet.DataHub.Aggregations.IntegrationEventListener/MeteringPoint/ConsumptionMeteringPointCreatedListener.cs
> +            var request = (ConsumptionMeteringPointCreatedEvent)await _messageExtractor.ExtractAsync(data).ConfigureAwait(false);
I don't really like this line here. Would it be possible to do something like this: `_messageExtractor.ExtractAsync<ConsumptionMeteringPointCreatedEvent>(data).ConfigureAwait(false)` so the type you expect to be returned are handled this way?

2021-12-03 07:50 UTC, dstsyst reviewed
Commented

2021-12-03 07:50 UTC, dstsyst commented on source/IntegrationEventListener/source/IntegrationEventListener.IntegrationTests/IntegrationEventListener.IntegrationTests.csproj
> +    <PackageReference Include="Energinet.DataHub.Core.FunctionApp.TestCommon" Version="1.3.0-alpha-20211202T230358" />
We must release TestCommon v1.3.0 and update the reference, before we close this PR

2021-12-06 13:55 UTC, johevemi approved these changes

2021-12-06 14:03 UTC, merged