Bug/122560 error with dbr sending result
Energinet-DataHub/geh-aggregations pull request #56
Opened 2021-04-14 12:55 UTC by kristianschneider

This PR fixes an issue where the databricks  job could not deliver its result back to the coordinator

2021-04-14 19:10 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Energinet-DataHub/geh-aggregations?pullRequest=56) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Energinet-DataHub/geh-aggregations?pullRequest=56) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Energinet-DataHub/geh-aggregations?pullRequest=56) it.</sub>

2021-04-15 06:10 UTC, mknic requested changes

2021-04-15 06:10 UTC, mknic commented on source/coordinator/GreenEnergyHub.Aggregation.Infrastructure/ServiceBusProtobuf/ServiceBusChannel.cs
> +                        _logger.LogInformation($"Dequeue {messages.Count}");
We shouldn't use string interpolation in log messages, right? I remember @jonasdmoeller mention that this at some point.

2021-04-15 07:29 UTC, kristianschneider commented on source/coordinator/GreenEnergyHub.Aggregation.Infrastructure/ServiceBusProtobuf/ServiceBusChannel.cs
> +                        _logger.LogInformation($"Dequeue {messages.Count}");
There is something about that, but I have experienced that parameters give weird output in the logstream

2021-04-15 07:45 UTC, mknic commented on source/coordinator/GreenEnergyHub.Aggregation.Infrastructure/ServiceBusProtobuf/ServiceBusChannel.cs
> +                        _logger.LogInformation($"Dequeue {messages.Count}");
I think we need to change the log messages to the format `_logger.LogInformation("Dequeue {messages.Count}", messages.Count);`

Otherwise, we don't get the benefits from using Serilog. If you do it in this PR or creates an issue to make this consistent in the repo is up to you.

2021-04-15 08:57 UTC, kristianschneider commented on source/coordinator/GreenEnergyHub.Aggregation.Infrastructure/ServiceBusProtobuf/ServiceBusChannel.cs
> +                        _logger.LogInformation($"Dequeue {messages.Count}");
I've added the formatting

2021-04-15 09:25 UTC, mknic requested changes

2021-04-15 09:25 UTC, mknic commented on source/coordinator/GreenEnergyHub.Aggregation.Infrastructure/ServiceBusProtobuf/ServiceBusChannel.cs
> +                _logger.LogInformation($"Done Sending {dataList.Count()} messages it took {sw.ElapsedMilliseconds} ms");
If we could have the last ones in this file fixed as well, I'm happy :-)

2021-04-15 09:25 UTC, mknic commented on source/coordinator/GreenEnergyHub.Aggregation.Infrastructure/ServiceBusProtobuf/ServiceBusChannel.cs
> +                _logger.LogError(e, $"Got an error in ServiceBusChannel when trying to write {e.Message}");
and this

2021-04-15 09:25 UTC, mknic commented on source/coordinator/GreenEnergyHub.Aggregation.Infrastructure/ServiceBusProtobuf/ServiceBusChannel.cs
> +                _logger.LogInformation($"Done Sending {data.Length} it took {sw.ElapsedMilliseconds} ms");
and this

2021-04-15 10:08 UTC, johevemi approved these changes

2021-04-15 10:09 UTC, mknic approved these changes
LGTM

2021-04-15 10:12 UTC, merged