Kristianschneider/store specific aggregation results
Energinet-DataHub/geh-aggregations pull request #65
Opened 2021-04-20 12:21 UTC by kristianschneider

This PR changes how the databricks job handles results. 
In preparation for refactoring of the coordinator.
The changes now store the results as snappy compressed json in the input container.

2021-04-21 10:48 UTC, mknic requested changes

2021-04-21 10:52 UTC, kristianschneider commented on .github/workflows/aggregation-job-infra-cd.yml
> +          # {
Because the deployment pipeline currently has a problem where the U environment is depended on the other environments and this means we cant deploy properly. So for now we are going to just U

2021-04-21 11:00 UTC, mknic commented on build/databricks_aggregation_cluster/main.tf
> +      package = "azure-storage-blob==12.8.0"
I fixed this in another PR

2021-04-21 11:00 UTC, mknic commented on build/databricks_aggregation_cluster/main.tf
> +      package = "python-snappy==0.6.0"
I fixed this in another PR

2021-04-21 11:09 UTC, mknic approved these changes

2021-04-21 11:44 UTC, jonasdmoeller commented on .github/workflows/aggregation-job-infra-cd.yml
> +          # {
Is it possible to leave a comment in the code explaining why this is temporarily disabled?

2021-04-21 11:55 UTC, ZavezX commented on .github/workflows/aggregation-job-infra-cd.yml
> +          # {
Does this mean that we can't deploy the code to a test environment?

2021-04-21 11:55 UTC, ZavezX commented on source/databricks/aggregation-jobs/aggregation_trigger.py
> +path = resultPath + "/" + nowstring + "/.json.snappy"
```suggestion
```

2021-04-21 12:20 UTC, jonasdmoeller requested changes

2021-04-21 12:20 UTC, jonasdmoeller commented on source/databricks/aggregation-jobs/aggregation_trigger.py
> +coordinatorService = CoordinatorService(args)
blob_service and coordinator_service

2021-04-21 12:20 UTC, jonasdmoeller commented on source/databricks/aggregation-jobs/aggregation_trigger.py
> +resultPath = "Results"
result_path

2021-04-21 12:42 UTC, ZavezX commented on source/databricks/aggregation-jobs/aggregation_trigger.py
> +blobService = BlobService()
You have a good point there Jonas👍

2021-04-21 12:58 UTC, kristianschneider commented on .github/workflows/aggregation-job-infra-cd.yml
> +          # {
I've found a different approach with Rene. I'll revert it

2021-04-21 13:05 UTC, kristianschneider commented on source/databricks/aggregation-jobs/aggregation_trigger.py
> +coordinatorService = CoordinatorService(args)
👍

2021-04-22 08:51 UTC, kristianschneider commented on source/databricks/aggregation-jobs/aggregation_trigger.py
> +blobService = BlobService()
A different concept has been made

2021-04-22 08:51 UTC, kristianschneider commented on source/databricks/geh_stream/aggregation_utils/services/blob_service.py
> +class BlobService:
sorted

2021-04-22 09:31 UTC, jonasdmoeller commented on source/databricks/geh_stream/aggregation_utils/services/blob_service.py
> +    blob_client.upload_blob(snappyData)
```suggestion
    container_name = args.input_storage_container_name
    json_obj = data.toJSON().collect()
    json_str = json.dumps(json_obj)
    snappy_data = snappy.compress(json_str)
    blob_service_client = BlobServiceClient.from_connection_string(CONNECTIONSTRING)
    blob_client = blob_service_client.get_blob_client(container=container_name, blob=blob_name)
    try:
        blob_client.get_blob_properties()
        blob_client.delete_blob()
    except ResourceNotFoundError:
        pass
    blob_client.upload_blob(snappy_data)
```

2021-04-22 11:11 UTC, jonasdmoeller approved these changes

2021-04-22 11:52 UTC, merged