Feature/123831 coordinator cleanup
Energinet-DataHub/geh-aggregations pull request #66
Opened 2021-04-21 07:13 UTC by jonasdmoeller

## Description

The aggregation coordinator solution was created without using the solution template, so it was missing some setup configurations, i.e. stylecop ruleset. This PR adds the missing components and fix warnings that comes with it.

## References

* #0000

2021-04-21 07:56 UTC, mknic reviewed
LGTM. I have a couple of comments/questions though.

2021-04-21 07:56 UTC, mknic commented on source/coordinator/GreenEnergyHub.Aggregation.Application/Coordinator/CoordinatorService.cs
> +            var list = await client.Clusters.List(cancellationToken).ConfigureAwait(false);
Did you come to a conclusion on when to use `ConfigueAwait(false)`?

2021-04-21 07:56 UTC, mknic commented on source/coordinator/GreenEnergyHub.Aggregation.Infrastructure/StartupConfig.cs
> -            if (string.IsNullOrEmpty(connectionString))
Why were all the conditions removed?

2021-04-21 08:02 UTC, johevemi approved these changes

2021-04-21 08:54 UTC, kristianschneider requested changes
I have a set of comments

2021-04-21 08:54 UTC, kristianschneider commented on source/coordinator/GreenEnergyHub.Aggregation.Application/Coordinator/Handlers/AdjustedFlexConsumptionHandler.cs
> +            return (from energySupplier in list.GroupBy(hc => hc.EnergySupplierMarketParticipantMRID)
Have you measured the performance of these expressions vs the loops?
I have a concern that this could be slower

2021-04-21 08:54 UTC, kristianschneider commented on source/coordinator/GreenEnergyHub.Aggregation.Coordinator/CoordinationTriggers.cs
> -            Enum.TryParse(processTypeString, out ProcessType processType);
This should be with Task.run to spawn a new thread. Otherwise, the Ok result could be delayed beyond the request timeout of the function. Please revert back

2021-04-21 08:54 UTC, kristianschneider commented on source/coordinator/GreenEnergyHub.Aggregation.Coordinator/CoordinationTriggers.cs
> -                Task.Run(async () => _coordinatorService.HandleResultAsync(decompressedReqBody, resultId, processType, startTime, endTime, cancellationToken), cancellationToken);
As previously task.run should be used here

2021-04-21 08:54 UTC, kristianschneider commented on source/coordinator/GreenEnergyHub.Aggregation.Coordinator/Startup.cs
> +            using var telemetryConfiguration = TelemetryConfiguration.CreateDefault();
Could *using* brake the lifespan of the telemetryConfiguration object ? So that perhaps later when we do telemetry it could die because the object has been disposed ?

2021-04-21 08:54 UTC, kristianschneider commented on source/coordinator/GreenEnergyHub.Aggregation.Infrastructure/ServiceBusProtobuf/ServiceBusChannel.cs
> +        public async ValueTask DisposeAsync()
Where does this stem from?

2021-04-21 12:22 UTC, jonasdmoeller commented on source/coordinator/GreenEnergyHub.Aggregation.Application/Coordinator/CoordinatorService.cs
> +            var list = await client.Clusters.List(cancellationToken).ConfigureAwait(false);
Yes. Søren had a good point mentioning, that we actually do not know how this code will be used by any consumers. So the correct approach is to use ConfigureAwait(false) on all await calls. I've also checked with team Volt and they generally follow the same approach.

2021-04-21 12:26 UTC, jonasdmoeller commented on source/coordinator/GreenEnergyHub.Aggregation.Application/Coordinator/Handlers/AdjustedFlexConsumptionHandler.cs
> +            return (from energySupplier in list.GroupBy(hc => hc.EnergySupplierMarketParticipantMRID)
No I haven't. But I think the main concern here is readability. I previously asked if we preferred LINQ in these cases, and thought that was the general consensus. But if that's not the case, it is fine by me that we go back to nested statements.

2021-04-21 12:34 UTC, ZavezX commented on source/coordinator/GreenEnergyHub.Aggregation.Infrastructure/ServiceBusProtobuf/ServiceBusChannel.cs
> +        }
What is this exactly?

2021-04-21 12:45 UTC, jonasdmoeller commented on source/coordinator/GreenEnergyHub.Aggregation.Coordinator/CoordinationTriggers.cs
> -            Enum.TryParse(processTypeString, out ProcessType processType);
But StartAggregationJobAsync(...) already executes in a different thread. If we want to continue and return Ok result before it finishes, we should simply not await it.

What this does is Task.Run(..) takes an idle thread from the thread pool and from there makes a call to the async method without awaiting it. But it is not necessary to make a thread that makes a thread, as the same thing can be achieved with only one.

Or am I missing something? I'm not a multithreading expert in C#, so I may be wrong.

2021-04-21 12:51 UTC, jonasdmoeller commented on source/coordinator/GreenEnergyHub.Aggregation.Coordinator/Startup.cs
> +            using var telemetryConfiguration = TelemetryConfiguration.CreateDefault();
We only use the TelemetryConfiguration to inject the instrumentation key. So it is only the instantiated object that is disposed in the garbage collection, if that's what you mean?

2021-04-21 12:52 UTC, ZavezX commented on source/coordinator/GreenEnergyHub.Aggregation.Application/Coordinator/Handlers/AdjustedFlexConsumptionHandler.cs
> +            return (from energySupplier in list.GroupBy(hc => hc.EnergySupplierMarketParticipantMRID)
I prefer the nested statements for readability reasons, but let's take it up with the other developers.

2021-04-21 12:55 UTC, jonasdmoeller commented on source/coordinator/GreenEnergyHub.Aggregation.Infrastructure/StartupConfig.cs
> -            if (string.IsNullOrEmpty(connectionString))
We do not fetch environment variable using fallback values, so these methods are never used. Unused code should not end in production unless it is purposely left out using a feature flag.
I think it is a leftover of the copy/paste from our Esett solution

2021-04-21 12:56 UTC, jonasdmoeller commented on source/coordinator/GreenEnergyHub.Aggregation.Coordinator/CoordinationTriggers.cs
> -                Task.Run(async () => _coordinatorService.HandleResultAsync(decompressedReqBody, resultId, processType, startTime, endTime, cancellationToken), cancellationToken);
See previous answer

2021-04-21 13:07 UTC, jonasdmoeller commented on source/coordinator/GreenEnergyHub.Aggregation.Infrastructure/ServiceBusProtobuf/ServiceBusChannel.cs
> +        public async ValueTask DisposeAsync()
I did not change the WriteBulkAsync if thats what you refer to. That may be github experiencing a glitch in the matrix.
If you refer to the DisposeAsync method, see my comment on Lasses question below.

2021-04-21 13:07 UTC, jonasdmoeller commented on source/coordinator/GreenEnergyHub.Aggregation.Infrastructure/ServiceBusProtobuf/ServiceBusChannel.cs
> +        }
_client and _sender are disposable members of the class, and hence should be disposed when garbage collected. The GC.SuppressFinalize tells the GC, that this object is already disposed and prevents it from happening twice.

2021-04-22 09:48 UTC, kristianschneider approved these changes

2021-04-22 09:48 UTC, merged