Feature/distribution list to grid companies stub
Energinet-DataHub/geh-aggregations pull request #77
Opened 2021-05-04 10:33 UTC by kristianschneider

This implements a stub for the distrubutionlist service as per
https://dev.azure.com/energinet/Datahub/_boards/board/t/Joules/Stories/?workitem=122977

2021-05-04 11:36 UTC, ZavezX requested changes
I have a few comments based on naming convention and some questions regarding that topic. I have also suggested a different approach to solve the task entirely.

2021-05-04 11:36 UTC, ZavezX commented on source/coordinator/GreenEnergyHub.Aggregation.Application/Coordinator/Strategies/AdjustedFlexConsumptionStrategy.cs
> +                        RecipientPartyIdMrid = _distributionListService.GetDistributionItem(first.MeteringGridAreaDomainMRID),
There is a bit of confusion surrounding naming convention here. In this code block the end part of properties are done in three different ways. `MRid`, `MRID` and `Mrid`. Let's go with one of them.

2021-05-04 11:36 UTC, ZavezX commented on source/coordinator/GreenEnergyHub.Aggregation.Application/Coordinator/Strategies/AdjustedHourlyProductionStrategy.cs
> +                        RecipientPartyIdMrid = _distributionListService.GetDistributionItem(first.MeteringGridAreaDomainMRID),
Same goes here as mentioned above.

2021-05-04 11:36 UTC, ZavezX commented on source/coordinator/GreenEnergyHub.Aggregation.Application/Coordinator/Strategies/FlexConsumptionStrategy.cs
> +                        RecipientPartyIdMrid = _distributionListService.GetDistributionItem(first.MeteringGridAreaDomainMRID),
And here.

2021-05-04 11:36 UTC, ZavezX commented on source/coordinator/GreenEnergyHub.Aggregation.Application/Coordinator/Strategies/HourlyConsumptionStrategy.cs
> +                        RecipientPartyIdMrid = _distributionListService.GetDistributionItem(first.MeteringGridAreaDomainMRID),
Here as well.

2021-05-04 11:36 UTC, ZavezX commented on source/coordinator/GreenEnergyHub.Aggregation.Application/Coordinator/Strategies/HourlyProductionStrategy.cs
> +                        RecipientPartyIdMrid = _distributionListService.GetDistributionItem(first.MeteringGridAreaDomainMRID),
Also here.

2021-05-04 11:36 UTC, ZavezX commented on source/coordinator/GreenEnergyHub.Aggregation.Application/Services/DistributionItem.cs
> +        public string RecipientPartyId { get; set; }
I think we need to stream line our naming conventions within this domain. I'm not a fan of these names. We could at this point maybe consider to take a look at the proposed domain language described in this document: https://github.com/Energinet-DataHub/green-energy-hub/blob/main/docs/domain-language-guide-book.md

2021-05-04 11:36 UTC, ZavezX commented on source/coordinator/GreenEnergyHub.Aggregation.Application/Services/DistributionItem.cs
> +        public string RecipientPartyId { get; set; }
We should also only need two properties in this class, one for grid area and one for receiver.

2021-05-04 11:36 UTC, ZavezX commented on source/coordinator/GreenEnergyHub.Aggregation.Application/Services/DistributionListService.cs
> +  },
Instead of using JSON as data, we could consider storing the data in a database instead, maybe SQL, as we would likely need a SQL database in the future to store metadata for aggregations.

2021-05-04 11:36 UTC, ZavezX commented on source/coordinator/GreenEnergyHub.Aggregation.Application/Services/DistributionListService.cs
> +  },
What exactly is the point in the single `'` for both `ORGANISATION_ID` and `RecipientPartyID_mRID`?

2021-05-04 11:36 UTC, ZavezX commented on source/coordinator/GreenEnergyHub.Aggregation.Application/Services/DistributionListService.cs
> +        var item = _listOfDistributionItems.SingleOrDefault(d => d.GridAreaCode.ToString().Equals(gridAreaCode));
Why have `gridAreaCode` parameter as string when it is defined in the data as int?

2021-05-04 11:36 UTC, ZavezX commented on source/coordinator/GreenEnergyHub.Aggregation.Domain/AggregatedMeteredDataTimeSeries.cs
> +        public string RecipientPartyIdMrid { get; set; }
Same with naming mentioned earlier.

2021-05-04 11:41 UTC, ZavezX commented on source/coordinator/GreenEnergyHub.Aggregation.Application/Services/DistributionItem.cs
> +        public string RecipientPartyId { get; set; }
Another possible solution could be to just ask an endpoint or a service bus or something for the data, instead of storing the data in our domain?

2021-05-04 11:41 UTC, ZavezX commented on source/coordinator/GreenEnergyHub.Aggregation.Application/Services/DistributionListService.cs
> +  },
Another possible solution could be to just ask an endpoint or a service bus or something for the data, instead of storing the data in our domain?

2021-05-04 12:05 UTC, kristianschneider commented on source/coordinator/GreenEnergyHub.Aggregation.Application/Services/DistributionListService.cs
> +  },
This is a dumb stub for future data, so we should not spend more effort on it. 
The ' was a typo in the imported data. now fixed.
We will get this data elsewhere once the market role domain has implemented it.

2021-05-04 12:13 UTC, ZavezX requested changes

2021-05-04 12:13 UTC, ZavezX commented on source/coordinator/GreenEnergyHub.Aggregation.Application/Coordinator/Strategies/AdjustedFlexConsumptionStrategy.cs
> +                        BalanceResponsiblePartyMarketParticipantmRID = first.BalanceResponsiblePartyMarketParticipantmRID,
Great that the naming is now coinsistent, but I think we should stick to `PascalCase` instead, as this mix is not good for readability. Example on suggested change would be `BalanceResponsiblePartyMarketParticipantmRID ->BalanceResponsiblePartyMarketParticipantMrId` or better yet, get rid of the `Mr` part all together?

2021-05-04 12:13 UTC, ZavezX commented on source/coordinator/GreenEnergyHub.Aggregation.Domain/AggregatedMeteredDataTimeSeries.cs
> +        public string BalanceSupplierPartyMarketParticipantmRID { get; set; }
We refer to this as `EnergySupplier` instead of `BalanceSupplier` elsewhere in the code, which one do you prefer?

2021-05-04 12:18 UTC, ZavezX commented on source/coordinator/GreenEnergyHub.Aggregation.Application/Services/DistributionListService.cs
> +  },
I know that we can't create the final solution now, but I'm just qustioning whether the preferred way is to store the data ourselves somehow or if we would prefer to get the data from Market Role domain some other way with an http call or via a service bus.

2021-05-04 13:06 UTC, kristianschneider commented on source/coordinator/GreenEnergyHub.Aggregation.Application/Services/DistributionListService.cs
> +  },
Since we know so little about the future of this, we'll keep it at this for now

2021-05-04 13:09 UTC, kristianschneider commented on source/coordinator/GreenEnergyHub.Aggregation.Application/Services/DistributionListService.cs
> +        var item = _listOfDistributionItems.SingleOrDefault(d => d.GridAreaCode.ToString().Equals(gridAreaCode));
Since in the calling data it is a string.
Question is whether gridareas always are numbers or could be something else, so I think providing a string down to this level gives the most flexibility

2021-05-04 13:11 UTC, kristianschneider commented on source/coordinator/GreenEnergyHub.Aggregation.Application/Coordinator/Strategies/AdjustedFlexConsumptionStrategy.cs
> +                        BalanceResponsiblePartyMarketParticipantmRID = first.BalanceResponsiblePartyMarketParticipantmRID,
My impression is that this is CIM convention which we want to try to use as much as possible. 
But I might be mistaken?

2021-05-04 13:13 UTC, kristianschneider commented on source/coordinator/GreenEnergyHub.Aggregation.Domain/AggregatedMeteredDataTimeSeries.cs
> +        public string BalanceSupplierPartyMarketParticipantmRID { get; set; }
It stems from this:
https://dev.azure.com/energinet/Datahub/_boards/board/t/Joules/Stories/?workitem=112973

2021-05-05 07:14 UTC, ZavezX approved these changes

2021-05-06 07:53 UTC, ftoft approved these changes

2021-05-06 08:38 UTC, merged