Feature/123333 verify net exchange
Energinet-DataHub/geh-aggregations pull request #78
Opened 2021-05-04 12:20 UTC by jonasdmoeller

## Description

Added strategy for handling aggregation results for net exchange (step 1 and 2)

## References

* #0000

2021-05-04 13:17 UTC, kristianschneider approved these changes

2021-05-05 08:16 UTC, ZavezX requested changes
Some minor things and a general comment on a suggested change, that we don't necessarily need to change in this PR, it's just meant as a discussion point.

2021-05-05 08:16 UTC, ZavezX commented on source/coordinator/GreenEnergyHub.Aggregation.Tests/AggregationHandlerTests.cs
> +            message.Kind.ShouldBeEquivalentTo(23);
This assertion (and other assertions based on `Kind` and `Result`), should assert the actual value statet in the test data with all decimals as well. That would require the test data to be different as well with more diversion in decimal values.

2021-05-05 08:16 UTC, ZavezX commented on source/coordinator/GreenEnergyHub.Aggregation.Tests/Assets/ExchangeNeighbour.json
> +    "result": -32.000
Is the correct decimal precision three? If so, then the decimal values must have a value in order to test the output is correct after mapping is done.

2021-05-05 08:16 UTC, ZavezX commented on source/databricks/tests/aggregation_utils/aggregators/test_net_exchange_grid_area_aggregation.py
>          .add("result", DecimalType(38, 9))
Is this decimal precision representative of what we can expect the data to be?

2021-05-06 12:18 UTC, jonasdmoeller commented on source/coordinator/GreenEnergyHub.Aggregation.Tests/Assets/ExchangeNeighbour.json
> +    "result": -32.000
I created a new story to handle this subject:
[Decimal precision user story](https://dev.azure.com/energinet/Datahub/_backlogs/backlog/Joules/Stories/?workitem=127863)

2021-05-06 12:19 UTC, jonasdmoeller commented on source/databricks/tests/aggregation_utils/aggregators/test_net_exchange_grid_area_aggregation.py
>          .add("result", DecimalType(38, 9))
I created a new story to handle this subject:
[Decimal precision user story](https://dev.azure.com/energinet/Datahub/_backlogs/backlog/Joules/Stories/?workitem=127863)

2021-05-06 12:25 UTC, jonasdmoeller commented on source/coordinator/GreenEnergyHub.Aggregation.Domain/ResultMessages/AggregatedExhangeResultMessage.cs
> +    public class AggregatedExhangeResultMessage : AggregationResultMessage
Fixed

2021-05-06 12:30 UTC, jonasdmoeller commented on source/coordinator/GreenEnergyHub.Aggregation.Tests/AggregationHandlerTests.cs
> +            message.Kind.ShouldBeEquivalentTo(23);
I fixed this for `Result `assertion, but `Kind `is a hard coded integer value (for now).

2021-05-06 12:31 UTC, jonasdmoeller commented on source/coordinator/GreenEnergyHub.Aggregation.Application/Coordinator/Strategies/ExchangeStrategy.cs
> +        public override IEnumerable<IOutboundMessage> PrepareMessages(IEnumerable<ExchangeDto> aggregationResultList, ProcessType processType, string timeIntervalStart, string timeIntervalEnd)
I like the idea. Are you the one making a PR with said changes? :)

2021-05-06 18:29 UTC, mknic requested changes
Very nice job. Only a couple of small commit suggestions regarding the `...mRID` convention.

2021-05-06 18:29 UTC, mknic commented on source/coordinator/GreenEnergyHub.Aggregation.Domain/DTOs/ExchangeNeighbourDto.cs
> +        public string InMeteringGridAreaDomainMRID { get; set; }
```suggestion
        public string InMeteringGridAreaDomainmRID { get; set; }
```

2021-05-06 18:29 UTC, mknic commented on source/coordinator/GreenEnergyHub.Aggregation.Domain/DTOs/ExchangeNeighbourDto.cs
> +        public string OutMeteringGridAreaDomainMRID { get; set; }
```suggestion
        public string OutMeteringGridAreaDomainmRID { get; set; }
```

2021-05-06 18:29 UTC, mknic commented on source/coordinator/GreenEnergyHub.Aggregation.Domain/ResultMessages/AggregatedExchangeNeighbourResultMessage.cs
> +        public string InMeteringGridAreaDomainMRID { get; set; }
```suggestion
        public string InMeteringGridAreaDomainmRID { get; set; }
```

2021-05-06 18:29 UTC, mknic commented on source/coordinator/GreenEnergyHub.Aggregation.Domain/ResultMessages/AggregatedExchangeNeighbourResultMessage.cs
> +        public string OutMeteringGridAreaDomainMRID { get; set; }
```suggestion
        public string OutMeteringGridAreaDomainmRID { get; set; }
```

2021-05-07 06:11 UTC, ZavezX commented on source/coordinator/GreenEnergyHub.Aggregation.Domain/DTOs/ExchangeNeighbourDto.cs
> +        public string InMeteringGridAreaDomainMRID { get; set; }
I'm not a fan of this naming with the lower-case `m`, as it is not very readable.

2021-05-07 06:12 UTC, ZavezX commented on source/coordinator/GreenEnergyHub.Aggregation.Application/Coordinator/Strategies/ExchangeStrategy.cs
> +        public override IEnumerable<IOutboundMessage> PrepareMessages(IEnumerable<ExchangeDto> aggregationResultList, ProcessType processType, string timeIntervalStart, string timeIntervalEnd)
I'll create a story for it👍

2021-05-07 07:49 UTC, ZavezX commented on source/coordinator/GreenEnergyHub.Aggregation.Application/Services/GlnService.cs
> +        public static string GetGlnFromSupplierId(string supplierId)
Why was this changed to `static`?

2021-05-07 07:49 UTC, ZavezX commented on source/coordinator/GreenEnergyHub.Aggregation.Tests/AggregationHandlerTests.cs
> +                "2020-10-03T08:00:00.000Z").First();
We don't use extended ISO8601 for dates.

2021-05-07 08:01 UTC, mknic commented on source/coordinator/GreenEnergyHub.Aggregation.Domain/DTOs/ExchangeNeighbourDto.cs
> +        public string InMeteringGridAreaDomainMRID { get; set; }
@ZavezX Fair enough. This was just to avoid inconsistency in the great work @jonasdmoeller did on refactoring to use the same convention across the solution. I don't have an opinion if it should be lowercase `m` or not as long as it's consistent.

2021-05-07 08:15 UTC, jonasdmoeller commented on source/coordinator/GreenEnergyHub.Aggregation.Application/Coordinator/Strategies/AdjustedFlexConsumptionStrategy.cs
> +                        MeteringGridAreaDomainmRID = first.MeteringGridAreaDomainmRID,
Lets fix that in another pull request. For now we just need to be consistent.

2021-05-07 08:20 UTC, jonasdmoeller commented on source/coordinator/GreenEnergyHub.Aggregation.Application/Services/GlnService.cs
> +        public static string GetGlnFromSupplierId(string supplierId)
Because it does not access any member data

2021-05-07 08:32 UTC, jonasdmoeller commented on source/coordinator/GreenEnergyHub.Aggregation.Application/Coordinator/Strategies/ExchangeNeighbourStrategy.cs
> +                    Transaction = new Transaction(),
Fixed

2021-05-07 08:40 UTC, jonasdmoeller commented on source/coordinator/GreenEnergyHub.Aggregation.Tests/AggregationHandlerTests.cs
> +                "2020-10-03T08:00:00.000Z").First();
Fixed

2021-05-07 08:46 UTC, ZavezX commented on source/messaging/source/GreenEnergyHub.Messaging/MessageTypes/Common/MarketEvaluationPoint.cs
> +        public string MRID { get; }
```suggestion
        public string mRID { get; }
```

2021-05-07 08:50 UTC, jonasdmoeller commented on source/messaging/source/GreenEnergyHub.Messaging/MessageTypes/Common/MarketEvaluationPoint.cs
> +        public string MRID { get; }
This will give a compile error, as properties must start with capital :'(

2021-05-07 08:58 UTC, ZavezX approved these changes

2021-05-07 08:58 UTC, ZavezX commented on source/messaging/source/GreenEnergyHub.Messaging/MessageTypes/Common/MarketEvaluationPoint.cs
> +        public string MRID { get; }
Haha, I knew that, I just wanted you to write it😁 So all in all, our defined naming convention is flawed😁

2021-05-07 08:58 UTC, mknic approved these changes

2021-05-07 09:00 UTC, merged