Code coverage for Python and .NET
Energinet-DataHub/geh-aggregations pull request #83
Opened 2021-05-06 18:09 UTC by Sondergaard

## Description

Add support for code coverage for python and dotnet

*Why:*
We would like to visualise which areas of the codebase is covered with tests

*How is the coverage calculated:*
All logic deemed application or domain is marked as unit coverage. This means that it is only theses areas that are included when the total code coverage is calculated.

If some tests are not included in the CI step please write that in the comments and we will work on including them in the coverage report.

2021-05-06 18:41 UTC, mknic requested changes

2021-05-06 18:41 UTC, mknic commented on .github/workflows/codecov-ci.yml
> +        pip install coverage pytest-cov pyspark pandas wheel
We need to add `pytest-cov` to the [notice](https://github.com/Energinet-DataHub/geh-aggregations/blob/main/NOTICE.md) file. This might be relevant in other domains if a similar PR is done across all domains. 

Ref. y python package:
https://pypi.org/project/pytest-cov/

2021-05-06 18:41 UTC, mknic commented on .github/workflows/codecov-ci.yml
> +        uses: codecov/codecov-action@v1
This needs to be added to the [notice](https://github.com/Energinet-DataHub/geh-aggregations/blob/main/NOTICE.md) file.
Ref to github: https://github.com/codecov/codecov-action

2021-05-07 06:17 UTC, Sondergaard commented on .github/workflows/codecov-ci.yml
> +        pip install coverage pytest-cov pyspark pandas wheel
pytest-cov is now added to the notice file

2021-05-07 06:18 UTC, Sondergaard commented on .github/workflows/codecov-ci.yml
> +        uses: codecov/codecov-action@v1
Codecov-action is added to the notice file

2021-05-07 06:19 UTC, Sondergaard commented
@mknic - I have updated notice file with new packages

2021-05-07 06:56 UTC, mknic approved these changes

2021-05-07 06:58 UTC, mknic commented on NOTICE.md
> +| `coverlet.collector` | 3.0.3 | <https://www.nuget.org/packages/coverlet.collector/> | MIT |
Oh! This can be removed. It's already in the `Nuget package` section.

2021-05-07 06:58 UTC, mknic commented on NOTICE.md
> +| `codecov/codecov-action@v1` | 1.5.0 | <https://github.com/codecov/codecov-action> | MIT |
This should be moved to the `Github Actions` section 😄

2021-05-07 07:18 UTC, Sondergaard commented on NOTICE.md
> +| `coverlet.collector` | 3.0.3 | <https://www.nuget.org/packages/coverlet.collector/> | MIT |
Removed - I need to learn how to use page up/down to see all the content of a file :)

2021-05-07 07:19 UTC, Sondergaard commented on NOTICE.md
> +| `codecov/codecov-action@v1` | 1.5.0 | <https://github.com/codecov/codecov-action> | MIT |
Moved....

2021-05-07 07:57 UTC, ZavezX commented on codecov.yml
> +      - geh_stream/validation/
Does this mean that we need to update which paths to cover for unit tests manually if we add new folders?

2021-05-07 08:23 UTC, Sondergaard commented on codecov.yml
> +      - geh_stream/validation/
Yes - this file specifies how the code coverage should be calculated in each area.

2021-05-07 08:46 UTC, jonasdmoeller approved these changes

2021-05-07 08:52 UTC, merged