Feature/126056 datetime handling
Energinet-DataHub/geh-aggregations pull request #86
Opened 2021-05-07 10:25 UTC by ZavezX

## Description

Introduction of `Instant` in coordinator to handle date and time. The assumption here is that we use UTC date and time in all corners of the application and assumes that the input to the coordinator is in UTC date and time as well.

All dates are formatted in `ISO8601` general pattern going in and out of the system.

## References

[Story](https://dev.azure.com/energinet/Datahub/_boards/board/t/Joules/Stories/?workitem=126056)

2021-05-07 12:34 UTC, johevemi commented on source/databricks/aggregation-jobs/aggregation_trigger.py
> +sys.path.append(r'/workspaces/geh-aggregations/source/databricks')
```suggestion
# import sys
# sys.path.append(r'/workspaces/geh-aggregations/source/databricks')
```

2021-05-07 12:37 UTC, jonasdmoeller requested changes

2021-05-07 12:40 UTC, ZavezX commented on source/coordinator/GreenEnergyHub.Aggregation.Domain/DTOs/ExchangeDto.cs
>          public string MeteringGridAreaDomainmRID { get; set; }
I couldn't agree more!

2021-05-10 06:40 UTC, jonasdmoeller approved these changes

2021-05-10 08:46 UTC, merged