Feature/121789 send message from job time series eventhub
Energinet-DataHub/geh-aggregations pull request #89
Opened 2021-05-07 12:59 UTC by ftoft

## Description

Initial implementation of integration for gridloss and system correction timeseries, back to timeseries servicebus.
This is best effort, because timeseries service bus is not ready yet.

## References

* #0000

2021-05-07 13:02 UTC, kristianschneider commented on source/coordinator/GreenEnergyHub.Aggregation.Domain/GreenEnergyHub.Aggregation.Domain.csproj
> +      <HintPath>..\..\..\..\..\..\..\AppData\Roaming\JetBrains\Rider2020.3\azure-functions-coretools\3.0.3442\Newtonsoft.Json.dll</HintPath>
What is using newtonsoft?

2021-05-07 13:03 UTC, kristianschneider approved these changes
Looks OK. Note my question

2021-05-10 06:58 UTC, kristianschneider requested changes
I have a single question. Otherwise I think it is good to proceed

2021-05-10 07:17 UTC, ftoft commented on source/coordinator/GreenEnergyHub.Aggregation.Domain/GreenEnergyHub.Aggregation.Domain.csproj
> +      <HintPath>..\..\..\..\..\..\..\AppData\Roaming\JetBrains\Rider2020.3\azure-functions-coretools\3.0.3442\Newtonsoft.Json.dll</HintPath>
I was not used. I have removed it.

2021-05-10 07:54 UTC, kristianschneider approved these changes

2021-05-10 09:06 UTC, jonasdmoeller requested changes
Have you considered writing unit testing the introduced logic?

2021-05-10 09:06 UTC, jonasdmoeller commented on source/coordinator/GreenEnergyHub.Aggregation.Domain/MeteringPointMessage.proto
> +  string mRID = 1;
Properties should start with capital letter.

2021-05-10 09:06 UTC, jonasdmoeller commented on source/coordinator/GreenEnergyHub.Aggregation.Infrastructure/ServiceBusProtobuf/ServiceBusChannelBase.cs
> +    public abstract class ServiceBusChannelBase<T> : Channel, IAsyncDisposable
Did you see the other two implementation of the service bus channel (from batman and volt)? We think we could simplify this a lot.

2021-05-10 18:24 UTC, ZavezX requested changes

2021-05-10 18:24 UTC, ZavezX commented on source/coordinator/GreenEnergyHub.Aggregation.Coordinator/Startup.cs
> +            builder.Services.AddSingleton(x => new TimeseriesServiceBusChannel(connectionStringServiceBus, "timeseries", x.GetRequiredService<ILogger<TimeseriesServiceBusChannel>>()));
Naming is off here as well, should be `TimeSeriesServiceBusChannel`.

2021-05-12 11:12 UTC, johevemi commented on source/coordinator/GreenEnergyHub.Aggregation.Domain/MeteringPointMessage.proto
> +  string mRID = 1;
this is a proto file and it should reflect the real name of the property. The autogenerated code from this file will change it automatically from (mRID) to match .NET standards (MRID)

2021-05-12 12:05 UTC, ZavezX approved these changes

2021-05-12 12:51 UTC, ftoft commented on source/coordinator/GreenEnergyHub.Aggregation.Infrastructure/ServiceBusProtobuf/ServiceBusChannelBase.cs
> +    public abstract class ServiceBusChannelBase<T> : Channel, IAsyncDisposable
No. We have not looked in to it.

2021-05-12 12:53 UTC, ftoft commented on source/coordinator/GreenEnergyHub.Aggregation.Application/Coordinator/Strategies/CombinedGridLossStrategy.cs
> +        public override IEnumerable<IOutboundMessage> PrepareMessages(
Maybe it is a good idea, but can we take it in a other task?

2021-05-12 12:54 UTC, merged